/*
Copyright 2016 The Eyra Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
File author/s:
    Matthias Petursson <oldschool01123@gmail.com>
*/

insert into token (inputToken)
values
(' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed finibus risus. Sed a quam semper, scelerisque urna ac, dapibus nibh. Duis vel diam arcu. Pellentesque a tellus scelerisque, aliquet metus at, elementum felis. Pellentesque molestie sit amet magna quis tempus. Praesent sed lacus a enim euismod fermentum quis ut augue. Vestibulum eget iaculis erat, nec porta felis. Maecenas scelerisque placerat odio. In ornare ipsum nec diam ornare, euismod molestie velit auctor. Fusce egestas ipsum non odio aliquet pellentesque. Fusce vulputate egestas malesuada. Donec in accumsan erat. Integer mattis nulla in odio bibendum, in dignissim nibh lacinia. Aenean vel est vitae sem blandit semper.

Donec mauris augue, viverra quis dui sed, rutrum euismod dolor. Aenean felis augue, venenatis tempor convallis ac, maximus eget risus. Integer ornare enim quis pellentesque mollis. Curabitur id facilisis velit. Integer ullamcorper justo sed nunc congue condimentum. Nam congue facilisis tellus, ac luctus dolor vulputate nec. Sed neque diam, mollis vel suscipit ac, ultricies eu nulla. Sed turpis est, consectetur at aliquet nec, pulvinar eget nibh. Quisque vulputate blandit turpis vitae aliquet. Aliquam dapibus, nulla eget venenatis eleifend, mi lacus commodo ipsum, sit amet tincidunt enim purus nec libero. Pellentesque ligula massa, tincidunt ac purus id, vestibulum bibendum dolor. Proin ac massa mauris. Morbi vestibulum massa a orci feugiat scelerisque. Nam neque neque, rutrum ac ante in, sollicitudin varius lectus. Nullam suscipit dui at dolor egestas, ac congue urna facilisis. '),
('Mauris non laoreet dolor, ac dictum velit. Nam vel turpis mauris. Pellentesque vel elit elementum, semper nibh et, vehicula tortor. Integer nunc mauris, feugiat sed fermentum vitae, imperdiet et leo. Vivamus vulputate quam in urna scelerisque dignissim. Etiam risus ipsum, pellentesque quis enim sed, auctor finibus ante. In consequat sem aliquam rutrum pretium. Praesent lacus velit, semper id molestie a, pretium ut dolor. Cras et pulvinar lorem. Quisque eu est nulla. Mauris congue, ante vel pulvinar elementum, nunc sem iaculis ligula, sed maximus arcu nulla quis dolor. Proin lobortis purus quis enim hendrerit, fringilla gravida ex feugiat. Sed facilisis augue nec turpis convallis, ac placerat elit imperdiet. Fusce lacus risus, tempor sit amet elit eu, blandit suscipit nibh. '),
(' Mauris elementum, velit feugiat varius mattis, orci libero accumsan metus, nec semper magna ipsum ac magna. Cras rutrum magna quis auctor venenatis. Cras risus urna, tristique eu interdum ac, sollicitudin et purus. Maecenas ornare dignissim magna, quis molestie nisi fermentum sed. Nulla porta bibendum fringilla. Aenean vitae odio et mauris tempor ullamcorper. In nisl diam, interdum vitae facilisis et, interdum sit amet purus. Duis eget ullamcorper magna, eget facilisis tellus. Quisque tincidunt et metus at vulputate. Suspendisse pretium vel mi eu porttitor. Nulla suscipit condimentum turpis vel maximus. Maecenas quis ultricies orci, vel condimentum felis. Etiam iaculis urna sem, in faucibus quam pulvinar sit amet.

Aenean ac arcu lobortis, varius est luctus, gravida ante. In sed felis fermentum nulla pretium sodales a at enim. Etiam rutrum mauris sollicitudin sem vehicula, ut feugiat felis ullamcorper. Donec lobortis sed est non blandit. Donec bibendum odio ut interdum facilisis. Proin semper placerat augue, sit amet porttitor mauris pharetra et. Nunc nibh ex, euismod placerat nunc vel, placerat vehicula sapien. Curabitur in arcu vel nulla maximus ornare in ac turpis. Aliquam enim elit, aliquam lacinia sagittis eu, auctor ac nulla. Ut bibendum mi eu tincidunt posuere. Donec auctor non tellus vitae malesuada. Fusce feugiat justo sit amet purus sollicitudin volutpat. Vestibulum at purus non justo venenatis efficitur quis vel ipsum. Aliquam erat volutpat.

Sed id cursus mi. Integer rutrum neque tellus, in elementum purus porttitor vitae. Aenean varius erat at mollis rhoncus. Proin bibendum, orci eget commodo molestie, libero leo consectetur sem, et efficitur nunc justo vel dui. Aenean egestas justo ut massa volutpat, a rutrum mauris commodo. Morbi rhoncus ligula non tempor egestas. Nulla placerat mattis molestie. Praesent id ultrices mauris. Aenean dolor neque, bibendum sed sollicitudin quis, malesuada ut sapien. Duis pharetra purus a metus sagittis, et iaculis ante volutpat. Maecenas elementum enim eu blandit scelerisque. Aliquam eu nulla turpis. Mauris consequat, augue eu vehicula luctus, dui ipsum gravida velit, eu tempus mi urna sit amet odio. Fusce id vulputate diam. '),
('Aliquam dignissim augue leo. Ut quam sapien, fringilla nec eros vitae, commodo tempus nisi. Nunc eros justo, iaculis at venenatis ac, sagittis non nulla. Etiam eu pellentesque ante. Integer sed metus nunc. Sed sit amet elit vitae urna tincidunt dapibus. Praesent eget turpis velit. In ornare sem placerat lacus consectetur lacinia. Proin quam urna, lobortis ut elementum nec, rutrum eget massa. In pulvinar viverra nulla id dapibus. Suspendisse ullamcorper tempus accumsan. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris porta orci pulvinar, pellentesque risus eu, vestibulum ligula. Maecenas sed accumsan sem. Nunc pellentesque augue sed leo finibus, sed auctor dui mattis.'),
('

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque in sapien eu efficitur. Vivamus sit amet molestie neque. Praesent in lorem a urna rutrum ornare. Pellentesque ultricies commodo libero in bibendum. Aenean turpis eros, lacinia a sollicitudin eu, lacinia et tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut blandit tempus odio, a euismod eros varius sit amet. Cras auctor tortor ac nisl sagittis, sed consequat mauris auctor. Praesent ac fermentum felis. Aenean rutrum consequat viverra. Vestibulum enim neque, ultrices at nisl at, volutpat semper risus. Vestibulum sodales diam id nisl varius, vitae maximus mi gravida. Curabitur ac porta nunc, quis gravida odio. Praesent elementum erat eu pretium viverra. Aliquam erat volutpat.

Proin pretium sed quam et tempor. Aenean congue turpis a nisi tristique maximus. Aliquam nulla risus, volutpat semper tortor maximus, vulputate pharetra elit. Praesent sit amet elit metus. Phasellus non euismod justo. Aliquam sed metus eget ipsum blandit rutrum. Praesent pellentesque aliquam facilisis. Nam in pharetra felis, vitae posuere lectus. Mauris varius erat ipsum, ornare ultrices leo pellentesque ut. Suspendisse porta nisi eget turpis rhoncus aliquet. Cras mollis arcu quis vehicula elementum. Integer nulla felis, vulputate vel pretium quis, bibendum vel magna.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sodales id libero vel vulputate. Maecenas cursus varius elit, vel imperdiet neque fermentum at. Pellentesque lorem dolor, feugiat eu dictum sed, rhoncus eget arcu. Sed rhoncus, purus sit amet pharetra euismod, nulla augue vulputate nisi, in pharetra sapien purus at elit. Aenean quis rutrum ante. Nullam at nisi quis quam gravida tempus a sed nisl. Nullam sit amet turpis dui.

Donec sed mattis eros, a mattis ligula. Proin consectetur dolor sed magna fringilla tincidunt. Sed quis velit eget lectus mollis ullamcorper in a leo. Sed sit amet aliquet enim. Etiam semper vulputate justo vulputate hendrerit. Quisque quis tincidunt lectus. Suspendisse ligula nisi, molestie sit amet laoreet vel, pharetra eu purus. Etiam at tortor auctor nibh ornare malesuada eget eget lorem. Mauris tincidunt massa sem, sit amet ultricies eros semper ac. In ac urna ac diam tincidunt gravida at in metus. Suspendisse eget massa nisi. Vestibulum et aliquam erat, eu eleifend justo. Phasellus suscipit quam purus, ac rhoncus turpis lacinia id.

Pellentesque bibendum, leo in convallis suscipit, ligula turpis imperdiet tortor, ut eleifend purus mi ut augue. Mauris finibus dictum diam. Curabitur eget eros fringilla, ultricies purus at, blandit lacus. Vestibulum mattis, orci in mattis consequat, leo nulla placerat nisi, eget mattis massa mi quis nunc. Maecenas quis suscipit lectus. Vestibulum a cursus ex, at molestie massa. Cras est sem, mattis nec neque vitae, luctus vestibulum ex. Curabitur placerat eleifend aliquam. Curabitur lacinia vestibulum erat, eu porttitor tortor viverra et. Nullam enim nisi, porttitor sed ultricies ac, facilisis ac felis. '),
(' Proin pretium sed quam et tempor. Aenean congue turpis a nisi tristique maximus. Aliquam nulla risus, volutpat semper tortor maximus, vulputate pharetra elit. Praesent sit amet elit metus. Phasellus non euismod justo. Aliquam sed metus eget ipsum blandit rutrum. Praesent pellentesque aliquam facilisis. Nam in pharetra felis, vitae posuere lectus. Mauris varius erat ipsum, ornare ultrices leo pellentesque ut. Suspendisse porta nisi eget turpis rhoncus aliquet. Cras mollis arcu quis vehicula elementum. Integer nulla felis, vulputate vel pretium quis, bibendum vel magna.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sodales id libero vel vulputate. Maecenas cursus varius elit, vel imperdiet neque fermentum at. Pellentesque lorem dolor, feugiat eu dictum sed, rhoncus eget arcu. Sed rhoncus, purus sit amet pharetra euismod, nulla augue vulputate nisi, in pharetra sapien purus at elit. Aenean quis rutrum ante. Nullam at nisi quis quam gravida tempus a sed nisl. Nullam sit amet turpis dui.

Donec sed mattis eros, a mattis ligula. Proin consectetur dolor sed magna fringilla tincidunt. Sed quis velit eget lectus mollis ullamcorper in a leo. Sed sit amet aliquet enim. Etiam semper vulputate justo vulputate hendrerit. Quisque quis tincidunt lectus. Suspendisse ligula nisi, molestie sit amet laoreet vel, pharetra eu purus. Etiam at tortor auctor nibh ornare malesuada eget eget lorem. Mauris tincidunt massa sem, sit amet ultricies eros semper ac. In ac urna ac diam tincidunt gravida at in metus. Suspendisse eget massa nisi. Vestibulum et aliquam erat, eu eleifend justo. Phasellus suscipit quam purus, ac rhoncus turpis lacinia id. '),
('Ut commodo dui vitae quam ornare, ac finibus tellus dapibus. Nam vel feugiat felis, ultrices vulputate nisi. Fusce arcu nisl, consequat non fermentum ac, scelerisque et magna.'),
('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id metus vitae risus sodales ullamcorper. Proin enim odio, dictum nec consectetur nec, mollis sed magna. Vivamus a magna sit amet enim egestas fringilla. Ut et blandit quam, nec bibendum erat. Donec sem turpis, pharetra nec metus nec, molestie pellentesque tellus.'),
('Proin nisi diam, mattis ut massa ut, pharetra pulvinar metus. In lacus eros, auctor vitae est sed, tincidunt fringilla ex. Quisque sit amet sem ut massa facilisis scelerisque. Nullam hendrerit venenatis molestie. Aenean blandit ac dui id aliquet. Aliquam lorem lectus, imperdiet vitae ipsum et, fermentum tincidunt eros. In quam nunc, efficitur non condimentum a, accumsan id urna. Curabitur id diam bibendum, vulputate quam eget, bibendum felis.'),
('Morbi ultricies ex ipsum, vel viverra dolor aliquet in. Vestibulum posuere luctus leo, et lacinia tellus tincidunt et. Quisque eleifend elit at tincidunt dictum. Morbi dictum nunc sapien, eu volutpat nulla ultricies non. Cras vitae dapibus felis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin ligula augue, pellentesque eu fermentum non, placerat a massa. Duis lacinia nisi sit amet leo hendrerit auctor. Aliquam sit amet convallis purus, vel maximus mauris. Vivamus id orci ac purus suscipit rhoncus. Integer ut enim sit amet libero dictum euismod commodo vitae erat. Fusce vulputate tortor id gravida pharetra. Aenean eu molestie felis. Cras porta nulla in iaculis pharetra. '),
('Regular length'),
('Tokens must'),
('Also be here so you'),
('Can see the difference'),
('Mauris id metus vitae risus sodales ullamcorper.'),
('Vestibulum posuere luctus leo, et lacinia tellus tincidunt et.'),
('Quisque eleifend elit at tincidunt dictum. Morbi dictum nunc sapien, eu volutpat nulla ultricies non.');