insert into token (inputToken)
values
('Þegar þú röltir þarna vestur eftir áðan fauk í mig. '),
('Litli fautinn þinn, segir hann. '),
('Gunnar fór úr kuflinum og fauk úr honum aska mikil. '),
('Þilið fauk framan af bæjardyrunum. '),
('Þess vegna fauk í mig. '),
('Það fauk í hann kerling, sagði amma mín Sigríður. '),
('Enda fauk höfuðið af bolnum. '),
('Hún gat ekki skilið þetta og það fauk í mig. '),
('Við það fauk í hann: '),
('Ragnar fór að hlæja, hver rokan af annarri fauk út í loftið. '),
('Það fauk á hann heyvagn. '),
('Þetta endaði með því að það fauk í mig. '),
('Öxin beit vel og fauk af höfuðið og kom víðs fjarri niður. '),
('Það fauk í Emmu, svo kjánalegt sem það var. '),
('Þar stendur feitur fauti með pulsupakka í hendinni. '),
('Hann fékk sér gúlsopa af kaffinu. '),
('Hann tekur gúlsopa af bjórnum og strýkur froðu úr þykku rauðbrúnu yfirskeggi. '),
('Hann gúlpaði í sig og var innan stundar að sjá sofnaður. '),
('þurfti aðeins að handleika gúmendann til þess að fá hljóð úr honum. '),
('Vildi Gústi litli ekki koma? '),
('Ævaforn eins og gúmmífætt, ryðleitt og útdautt spendýr, sem sefur standandi. '),
('Hún helgaði sig Marteini innilega og líka Gústafi. '),
('Hann er með mér í þessu gúanófyrirtæki. '),
('Og þetta varð að fjörugum lafmóðum dvergadansi milli gúmmítrjánna. '),
('Grannholda maður á gúmmístígvélum bauð gott kvöld. '),
('Fyrir tólf árum dó þetta barn og hún geymir ennþá gúmmílakið. '),
('Hún settist upp í rúminu og leit út á gúmmítrén. '),
('Það er bók þarna á borðinu, Ferðir Gúllivers. '),
('Sjáðu til, ég þekki hann Gústaf. '),
('Þetta var fremur lítill grasivaxinn hóll, þar sem gamalt gúmmítré drúpti blöðum. '),
('Hann er í hvítum hlífðarslopp með málningarblettum og með gúmmíhanska á höndunum. '),
('Það liggur aldeilis vel á þér, sagði Gústaf. '),
('Og Gústaf svarar jafn alvarlega.'),
('Í kvöld ætlar Gústaf að kynna hann fyrir viðskiptafélögum sínum. '),
('Ólöf tók gúlsopa úr flöskunni og rétti Kollu hana. '),
('Íkornar þustu niður flekkótta boli gúmmítrjáa sem hölluðu sér upp í sólina. '),
('Hann skrúfaði tappann af og drakk gúlsopa og svo annan. '),
('Þar er silfur, kopar, saltpétur, gúanó. '),
('Þá vorum við Gústi tveir einir á vakt í brúnni. '),
('Ég hef ekki fundið gúanóeyju, sagði ég. '),
('Tveir sokknir gúlpar voru þar sem augasteinarnir áttu að vera. '),
('Láttu ekki einsog kjáni, Gústa, sagði móðir hennar höstug. '),
('Gekk svo einn undir tungli á gúmmískóm yfir freðnar mýrar innaf bænum. '),
('Fæ mér gúlsopa af rauðvíni. '),
('Gústaf var ánægður með það: '),
('Það var Halldór, kominn í olíukápu og gúmmístígvél. '),
('Þess vegna var það hátíð fyrir hana að hitta Gústaf. '),
('Ef Gústaf hefði boðið þeim upp á vínið? '),
('Síðan setti hann á sig gúmmíhanska og hófst handa. '),
('Gústaf varð vandræðalegur frammi fyrir þögn Ingu. '),
('Gústaf var að ná sér aftur á strik.'),
('Hún réttir Gústafi lítinn pakka: '),
('Móðirin heldur í höndina á Gústafi og kallar á Ingu. '),
('Magga rétti mér flösku og ég tók gúlsopa en. '),
('Hann fær sér gúlsopa af bjór. '),
('Hafði Gústa skotist til hennar og sagt frá heimkomunni. '),
('Þetta er eins og í fyrra þegar gúmmíbátinn rak á land. '),
('Gamall skíðasleði, hlutar af þreskivél, fúnar trjágreinar og gúmmístígvél. '),
('Þær hitta nágrannakonu í gúmmístígvélum sem er á leið í fjós. '),
('Hann klæddi sig úr gúmmístígvélunum og úlpunni. '),
('Við mættum fá okkur gúlsopa en ekkert framyfir það. '),
('Það er ekki nóg að taka fullan gúlinn, Þura litla. '),
('Hún er í barnaverndinni, gútemplarareglunni og kirkjugarðsfélaginu. '),
('Tíkin birtist á hlaði blaut á feldinn með blautan gúmmískó í kjaftinum. '),
('Þá læddist hann inn á náttskyrtunni sem gúlpaði fyrir neðan maga. '),
('Skammt frá var Velutha að stytta sér leið gegnum gúmmítrén. '),
('Mér hefur alltaf þótt Gústaf fallegt nafn. '),
('Leðurhúfan á höfði, gleraugu, og sundblöðkurnar utan yfir gúmmískóna, nauðsynlegt hæðarstýri. '),
('Svartar gúmmíræmurnar féllu á gólfið. '),
('Hann var umkringdur hafsjó af hlykkjóttum gúmmíslöngum. '),
('Henni fannst hún hafa fundið frelsið í sambandi sínu við Gústaf. '),
('Þetta er eins og gúmmí. '),
('Hvers vegna það, ekki gúllas? '),
('Fyrsti brennheiti gúlsopinn kallar tár fram í augun. '),
('Ég er að spyrja þig, Gústi, þú varst fyrirliðinn. '),
('Yðar ágæti, sagði Gústaf dimmri röddu. '),
('En þú, Gústi, verður að borga tíu þúsund í sekt. '),
('Logarnir höfðu sleikt burt lakkið og gúmmíhandföngin á stýrinu voru bráðnuð. '),
('Varla hefði hann komið á sig gúmmíflibbanum í þeim troðningi.'),
('Gúmmískór bóndans eins og skáldið skildi við þá. '),
('Ég fæ mér gúlsopa af víninu. '),
('Þú komst inn í líf mitt eins og Gúlíver inn í Putaland. '),
('Í annarri fannst eintómt gúmmídrasl. '),
('Ég tek fatið með súru gúrkunum og ætla að rétta mömmu það. '),
('Það er sósa á sokkunum mínum og súr gúrka á skónum. '),
('Komdu með rauðkál í blússi, gúrku og púðursykur á kjötið. '),
('Hún sýslaði við gúrkuna og gat varla dulið sigurgleðina í svipnum. '),
('Hún snerti nýju klippinguna með gúrkuhendinni. '),
('Klessa af römmu gúrkufrauði sat dyggilega föst í hárinu. '),
('Hún horfði á Barböru flysja gúrkuna. '),
('Gular gúrkuhýðisflísar lágu á víð og dreif um borðið. '),
('Hún fékk sér kjöthleif með súrsaðri gúrku, týtuberjasultu og kartöflustöppu. '),
('Það sat enginn hjá í þeim Gúttóslag. '),
('Þegar hún fengi flöskuna og gúmtúttu yrði allt miklu betra. '),
('Æðsti heiður sem miklum konungum gat hlotnast var að nefnast ljónshjarta. '),
('Líklega hefði hann hlotið að sjá honum bregða. '),
('Aðeins tvisvar hlotnaðist mér að sjá hárið á henni. '),
('Nú hefir þú Þorsteinn hlotið lítinn hlut afls og vaxtar. '),
('Fyrir það hef ég hlotið fulla umbun. '),
('Það hefði hlotið að heyrast ef það hefði dottið dúnfjöður. '),
('Sveini hafði einhvern veginn hlotnast hestur úr eigu Bjargar. '),
('Nú hafði hún hlotið verri örlög en ég. '),
('Illt hefir jafnan af þér hlotist og þínum ráðum. '),
('Ég hafði hlotið minn dóm en vísindin náðuðu mig. '),
('Í vinnunni hef ég loksins hlotið náð hjá stelpunum. '),
('Hefir og þessi ógæfa af þér hlotist. '),
('Þá hafði alt farið vel og hann hlotið stórþakkir. '),
('Við það hlotnaðist henni styrkur og hamingja. '),
('En hvers vegna hefur þú hlotið sama hlutskipti? '),
('Hún sagði honum frá ungri konu sem hafði hlotnast blessun. '),
('Okkur hlotnast nýr ritstjóri í dag. '),
('Hún hafði hlotið að verða þess vís hversu ákaflega hann elskaði hana. '),
('Okkur hefur hlotnast stærsta gjöfin. '),
('Hún grátbað hann að hlíta þeim annars gæti illt af hlotist. '),
('Þegar hér var komið höfðu sex leikarar hlotið viðurkenninguna: '),
('Annar eins frami hafði Boggu aldrei hlotnast. '),
('Hlotnast mér sá heiður að fá að heimsækja þig bráðum aftur? '),
('Þér hefur hlotnast allnokkur heiður með boði Sigríðar. '),
('Hann hefur ekki hlotið fulla þjálfun , skrifaði Pétur. '),
('Afi sá gamla blökkumanninn hlaupa að eftirlitsmönnunum og reiða hlújárnið til höggs. '),
('Við erum með áfallahjálp til hlúa að örvæntingarfullum unglingum. '),
('Að elska, að finna æðanna slag, að æskunni í sálinni hlúa. '),
('Ég hef tekið á móti og reynt að hlúa að ótal börnum. '),
('Hann heyrði í móður sinni sem hlúði að honum. '),
('Annar við að hlúa að sjúkum, hinn að veita fólki nábjargirnar. '),
('Að okkur var hlúð á sjúkrahúsi og ráðsmaðurinn kallaði mig á eintal. '),
('Anna breiddi ofan á hann og hlúði að honum. '),
('Róið var í veg fyrir hann og hlúð að okkur á spítala. '),
('Þeir unnu með skóflum og hlújárnum. '),
('Ég sótti ábreiður úr horninu og við hlúðum vel að Jóni. '),
('Ég grét og hnaut um orðin í meira en klukkustund. '),
('Víðar og hnausþykkar buxur strekktust yfir rassinn.. '),
('Komnir í hús og þar bíður hnausþykkur grautur með mjólk út á. '),
('Það var orðið nærri albjart þegar Ari hnaut um eitthvað. '),
('Hnausþykkur reykjarmökkur haugaðist út úr kjallaranum. '),
('Og þær voru æðislegar með gula hnausþykka rjómanum úr skilvindunni. '),
('Kannast einhver við svona lagaðan hnaus? '),
('Undir morgun drattaðist hann upp stigann, hnaut og bölvaði. '),
('Blinduð, hnaut um gjallhaug, skyrpti ösku, gekk innar og grét. '),
('Sveinn hnaut og veltist um í svaðinu. '),
('Hnossgæti eins og þeir matreiða hann hérna. '),
('Þegar Ágústínus spurði hvað hnokkinn ætlaðist fyrir með holuna, svaraði hann keikur. '),
('Mannsheilinn fengi aldrei rúmað meira af guðdóminum en hola hnokkans af hafinu. '),
('Upp úr honum kemur hnoðinn. '),
('Og þú stóðst eftir með hnoðann. '),
('Hrappur leitar eftir þeim og finnur þau á hnotskóginum. '),
('Þarna stóðum við andspænis hvor öðrum fyrir framan hnoðnaglahurðina á dyrum hússins. '),
('Hákarl er mesta hnossgæti á Íslandi. '),
('Gísli leyfði þeim að þvo sér í framan og hnoðaðist með þá. '),
('Hver hleypur eftir sínu hnoða: '),
('Dætur hennar hétu Hnoss og Gersemi. '),
('Vonandi að þau detti ekki af í öllu þessu hnoði. '),
('Já, sagði Annika og hnoðaði snýtubréfið saman í kúlu. '),
('Ég norpaði úti obbann af nóttunni til að hljóta þetta hnoss. '),
('Ég hnoðaði fiðrið með hnefunum.'),
('Tómas fann hvernig hann hnoðaði karlfjandanum saman bak við stýrið. '),
('Sveinn leit til Bogga sem þuldi nefmæltur vegna hnoðrans í nösinni. '),
('Í vöggum hjá rúminu sváfu tveir ljóshærðir hnokkar svefni réttlátra. '),
('Amma egndi gildrurnar með kúlum sem hún hnoðaði úr mjöli. '),
('Hann kvað það vera orðum aukið, en víst væri hákarlinn hnossgæti. '),
('Hann var að vísu ekki stór, en hreinasta hnossgæti. '),
('Þarna þóttist ég sjá í hnotskurn muninn á þjóðarþeli frændþjóðanna. '),
('Á milli kindanna skoppuðu litlir, hvítir hnoðrar.'),
('Eldabuskan var búin að hnoða skömm hans í kökudeigið. '),
('Þetta er lífshlaup Jakobs í hnotskurn. '),
('Hann sofnaði og Þórkatla kom, smeygði í lófa hans hnoða. '),
('Alveg er þetta bróðir minn í hnotskurn. '),
('Hann bregður hönd inn á sig og réttir mér hnoða. '),
('Fugl þennan skírði ég hnotkráku sem var einstaklega viðeigandi nafn. '),
('Þar höfum við líf þitt í hnotskurn. '),
('Ég stend ein í afdrepinu með hnoðann í lófanum og kreisti. '),
('Svona er nútíminn í hnotskurn. '),
('Þau sem hrepptu hnossið voru þrjú.'),
('Gufustrókar ganga úr andliti Einars en máttlitlir hnoðrar úr vitum Maríu. '),
('Karl hnoðaði hárinu saman í hnykil og stakk því í vasann. '),
('En það hnussaði í lækninum.'),
('Það hnussar fyrirlitlega í Ragga. '),
('Eldabuskan sperrti fram barminn og hnussaði. '),
('Bóndinn hnussaði og unglingurinn leit snöggt á hann undan hnykluðum brúm. '),
('Haraldur sá Valgerði hnuggna og niðurdregna.'),
('Það hnussaði í Alla, fullum fyrirlitningar. '),
('Ég heyrði að Björg hnussaði oftar en einusinni. '),
('Þetta hnus hennar var gælunafnið mitt, hún kallaði mig hvolpinn sinn. '),
('Loks hnussaði í móður hennar, til að sýna uppsöfnuð vonbrigðin og fyrirlitninguna. '),
('Hláturinn var gleðisnauður og minnti helst á hnuss. '),
('Ekki verða orðalaus og hnuggin á sunnudegi, bað Magga. '),
('Nei, sagði Sveinn og hnussaði í gegnum nefið. '),
('Hentu þeim út, hnussaði í Stínu sem sneri sér að Erlendi. '),
('Engar þakkir, hnussaði móðir mín, bara mikið af gjöfum. '),
('Jæja, hnussar Gabríela eins og við sjálfa sig. '),
('Jamm, hér er víst hægt að hnjóta um hnullung, sagði hann. '),
('Hún færði sig varlega nær til að hnusa af þessu. '),
('Stúdentinn pantaði tvo fordrykki og horfði hnugginn í augun á Kristínu: '),
('Friðrik talaði, hnugginn og beygður, og sagði frá ógæfu sinni. '),
('Efst í fjörunni lá hrönn af bláglærum hnullungum, niðurmuldum hafís. '),
('Munaðarlausir hestar hnusa af þeim. '),
('Sporhundar hnusuðu í kringum hliðið. '),
('Nei, aldeilis ekki, hnussaði mamma sannfærandi og ákveðin. '),
('Blámi sperrti eyru og skott og hnusaði út í loftið.'),
('Nei, sagði hann og leit hnugginn framan í hana. '),
('Ég leyfði mér að hnussa og segja: '),
('Og enn hnussar kerling og heldur áfram að rausa. '),
('Bárður leit á útvarpstækið, hristi hausinn og hnussaði. '),
('Lögreglan kom semsagt, hnusaði svolítið og fór? '),
('Katrín hnussaði fyrirlitlega og sagði svo: '),
('Hirðklíkan í Pétursborg fyrirgefur mér þetta aldrei, sagði hann hnugginn. '),
('Það hnussaði í gamla manninum; '),
('Hún hnusaði enn út í loftið. '),
('Það hnussaði í móður hennar. '),
('Þegar Óðinn ágirnist djásn Freyju er Loki látinn hnupla því. '),
('Rakkinn hnussaði út um nefið hor. '),
('Hann hnussaði, hallaði undir flatt og beið eftir viðbrögðum frá henni. '),
('Við héldum ótrauðir áfram, hnutum um lík en heyrðum loks rödd. '),
('Hún togaði í flækta fléttuna og hnussaði. '),
('Já þið getið látið eins og trúðar og fífl, hnussaði í Ólafi. '),
('Mér heyrist hnussa í dóttur minni. '),
('Jarðvegurinn var sendinn þar sem við tókum hnullungana. '),
('Það hnussaði í henni um leið og hún henti frá sér beininu. '),
('Ég faldi vel að ég hnuplaði stöku sinnum. '),
('Bleikálótta tryppið hnusaði að hvolpinum. '),
('Matti losar hnútinn sem ég hafði bundið. '),
('Hann tók svo fast um stýrið að hnúarnir hvítnuðu. '),
('Sá sem gerði þetta er öllum hnútum kunnugur, sagði hann. '),
('Sigríður fékk hnút í magann þegar hún mætti honum. '),
('Litla barnið er með hnúð. '),
('Tískulína þess tíma krafðist þess að við hnýttum hnútinn á hökubroddinum. '),
('Hárið var undið í hnút sem var festur með silfurprjónum. '),
('Hildur burstaði hárið á Hilmu og setti það upp í laglegan hnút. '),
('Ég hnýtti á hann hnút. '),
('Grýlan hún amma styður hnúa á borðsrönd. '),
('Holur hnúskóttur kálfinn var bleikur eins og almennilegir kálfar eiga að vera. '),
('Við höfðum unnið hnúk en fengum svo ekki að halda honum. '),
('Við afhentum fasistunum hnúkinn og þökkuðum fyrir lánið. '),
('Ó hvað bláminn var fallegur yfir Hnúknum! '),
('Ég var með skelfilegan hnút í maganum þegar mamma opnaði dyrnar. '),
('Ef til vill höfðu þeir snyrt betur hnúkinn sjálfan. '),
('Einn sonur hans hét Eyvindur lambi, annar Ölvir hnúfa. '),
('Lengst í fjarska var blár hnúkur og gnæfði yfir fjöllin í kring. '),
('Þá sá Ölvir hnúfa Solveigu og gerði sér títt um hana. '),
('Blái hnúkurinn sem Skari hafði bent á var fyrst milli tveggja fella. '),
('Hún fléttaði hárið í hnút í hnakkanum. '),
('Hnúkurinn blái var orðinn brúnn. '),
('Hann þagnaði og leit á hvíta hnúana. '),
('Enginn svaraði og hún hélt áfram með hnúana á borðinu: '),
('Hnúarnir hvítna og það smellur í axlarliðum. '),
('Með minni aðferð hafði ég höggvið á hnút þagnarinnar. '),
('Hnefarnir krepptust og hnúarnir hvítnuðu. '),
('Þó tekur fyrst í hnúkana þegar kvenfólkið verður altekið af þessu. '),
('Ungfrú Dagný sló mig á hnúa hægri handar. '),
('Hún settist upp og vafði hárið saman í hnút í hnakkanum. '),
('Reyndu að losa um hnútinn aftan á mér. '),
('Rauðir hnúðar, sætir á bragðið! '),
('Hún heldur áfram og nýr saman höndunum svo hnúarnir hvítna við átökin. '),
('Með þeim Ölvi hnúfu var félagsskapur mikill. '),
('Konan neri saman höndunum svo hnúarnir hvítnuðu. '),
('Hann fékk hnút í magann, þetta gerðist aðeins of hratt. '),
('Barði á hana með hnúunum og æddi af stað. '),
('Nú fann hún aftur fyrir hnút í maganum, kokið herptist. '),
('Hún réðst að honum með hnúum og hnefum. '),
('Eftir um daginn gekk Ölvir hnúfa til Þórólfs frænda síns. '),
('Þau hlóðu vörðu uppá hæsta hnúknum og kveiktu bál. '),
('Ég vef hárið í hnút undir hattinn. '),
('Sólin var að hverfa bak við hnúkana. '),
('Hann valhoppaði yfir hnútótta móa upp á lyngþúfur og ofan í grasdokkir. '),
('Þessi hnúkur þarna heitir Ármannsfell, og þarna er Meyjasæti. '),
('Nú sitja þeir allir veisluna, en í veislulokin er farið í hnútukast. '),
('Hárið var bundið í hnút. '),
('Hnúkar blikuðu uppi á milli stjarnanna. '),
('Lárus var með hnút í maganum. '),
('Þú getur jarðsungið á þér hnúana þess vegna! '),
('Handarbökin voru loðin fram á hnúa. '),
('Hann fann dálítinn hnúð á lærinu innanverðu. '),
('Jaðarinn féll niður á parti og dróst saman í hnút.'),
('Ferðin upp hnúkinn sóttist seint. '),
('Tvær vélbyssur uppi á hnúknum létu dæluna ganga móðursýkislega. '),
('Ekki leið á löngu þar til hnúkurinn var orðinn eins og eldfjall. '),
('Ég fékk bara hnút í magann og varð eitthvað svo ringluð. '),
('Hann er með meira en hnúð. '),
('Á hægri handleggnum var stór hnútur undir erminni.'),
('Maðurinn sleit hnútuna úr munni gömlu konunnar og kastaði í vaskinn. '),
('Hann teygði sig í hnúðinn og opnaði skápinn upp á gátt. '),
('Hver veit svosem hvernig lífið bindur sína hnúta. '),
('Hún barði sér á brjóst með hnúunum. '),
('Ég tók til snærisbút, hnútareipi og skæri sem Símon yfirfór vandlega. '),
('Hann gat ekki með nokkru móti leyst þennan hnút. '),
('Við þræddum götuna á gilsbotninum og nálguðumst hnúkinn. '),
('Syðsti raninn var á valdi óvinanna og gekk hann út frá hnúknum. '),
('Hnútan kemur á kinnbein Árna svo kjálkinn brotnaði í stykki. '),
('Hún fór þangað með hnút í maganum. '),
('Áhlaup okkar á hnúkinn hófst hins vegar ekki fyrr en klukkan 17. '),
('Skipun barst um að gera aftur áhlaup daginn eftir á hnúkinn. '),
('Þeir bræður Ölvir hnúfa og Eyvindur lambi dvöldust um hríð á Sandnesi. '),
('Svarti hnúðurinn á handfanginu var dottinn af. '),
('Presturinn ýtti með hnúunum við skarsúðinni í Kothaga og sagði: '),
('Ég bankaði eins og djöfulóð manneskja, með hnefa og hnúum! '),
('Allar taugar skruppu saman í harðan hnút einhvers staðar við þindina. '),
('En okkur hafði sama og ekkert miðað í áttina að hnúknum. '),
('Hann var allur í einum hnút og hélt um magann. '),
('Hnúturinn á bakinu hefur raknað. '),
('Þegar hann sá börnin krepptist eitthvað í hnút innra með honum. '),
('Nú var hann að fá hnút í magann. '),
('Hallgerður spennir greiparnar svo þétt saman að hnúarnir hvítna undan átakinu. '),
('Hún gældi við hnúðinn á gírstönginni með löngum, grönnum fingrunum. '),
('Það blæddi úr tveimur hnúum á vinstri hendi. '),
('Svartur hnúður - það var það síðasta - hnúður, mattur sem lín. '),
('Tvær ferðir kringum hnöttinn með heimsferðum Ingólfs. '),
('Upp af hverju þeirra steig draumur um líf á öðrum hnöttum. '),
('Allir riðu þeir vinnumennirnir í íslenskum hnökkum. '),
('Hundrað milljónir silfurgljáandi búka mynduðu satúrnusarhring umhverfis hnöttinn! '),
('Þú getur farið í flugvél kringum hnöttinn. '),
('Mig langar ekkert kringum hnöttinn, sagði ég. '),
('Allt í kringum hnöttinn voru sjávardýr farin að ganga á land. '),
('Samband þeirra bræðra var hnökrótt, ýmist með miklum kærleikum eða fullkomnum fáleikum. '),
('Reykskýið myndar svífandi hnött sem smám saman tekur á sig form Skugga. '),
('Gamla, hnöttótta höfuðið leit stolt í kringum sig: '),
('Konan reyndi að koma hugmyndum sínum hnökralaust á pappír. '),
('Varla siturðu sjálfur í tveim hnökkum! '),
('Hugsum okkur að úti í geimnum sé hnöttur þar sem mennirnir endurfæðast. '),
('Samvinnan í skemmunni var að mestu hnökralaus. '),
('Hver veit nema fiðrildi séu njósnarar af öðrum hnöttum. '),
('Hann er til að mynda eins og hnöllóttur eggskurmur. '),
('Ekki að ég myndi ferðast um hálfan hnöttinn. '),
('Höfuðið var hnöttótt, hárstæðið þakið ljósum hýjungi. '),
('Bláar æðar eins og hnökrótt prjónles upp eftir hálfglærum sköflungum. '),
('Hún strauk blíðlega stórt og hnöttótt höfuðið á honum. '),
('Svitadropar láku og hnöppuðust saman í polla. '),
('Í myrkrinu, undir bláu hnöppunum, eru fjöllin skuggamyndir, útlínur þeirra einsog málverk. '),
('Regndropar hnöppuðust á vaxhúð vængjanna. '),
('Þeir hnöppuðust á gleri krukkunnar í tágakörfunni. '),
('Skömmu síðar byrjaði regluleg bændaglíma og var kosið á hnöppum; '),
('En hún setti eitt skilyrði, hún vildi fá þau hrá. '),
('- En, sagði Sir Edmond, hvað ætlið þér að gera við hrá eistu? '),
('Ekki ætlið þér að snæða þau hrá? '),
('Ég gæti kannski bara keypt hráefnið og eldað sjálf. '),
('Fyrst var svolítill meðvitundarlaus hráki sem hét amaba. '),
('Hér voru í boði kindahausar, bæði hráir og sviðnir. '),
('Þokan var niðdimm og hráköld. '),
('Þetta októberkvöld sýndi sitt rétta andlit með hráslagakulda frá vatninu. '),
('Verkstjórinn kallaði ykkur á sinn fund og sagði að hráefnið væri eldfimt. '),
('Þá voru hvergi rúm eða hrákadallar eins og nú er. '),
('Svo upplýsi ég hann um hrikalegt, ótrúlegt hráefnið. '),
('Ég tróð magann fullan af grænmeti, þó hrátt væri. '),
('Þau komu á borðið ýmist harðsoðin eða svotil hrá. '),
('Saklausir menn lifa á hrámeti, spilltir sjóða. '),
('Hann smjattar áfergjulega á hrámetinu. '),
('Það var hráslagalegt og kalt. '),
('Þetta er hráskinnsleikur stórvelda eins og hver maður vissi. '),
('Þokan smaug inn og fyllti húsin með hráslaga, hrolli og rekju. '),
('Næturloftið er þrungið nístandi hráslaga. '),
('Þeim sem étur nýja og hráa selslifur verður aldrei misdægurt! '),
('Hrákadallurinn kom fljúgandi og fjóshaugurinn og bæjarlækurinn. '),
('Hljóð haustnóttin var hráköld og dimm. '),
('Ekkert var í afdrepinu nema bækur og blöð á gólfinu eins og hráviði. '),
('Steiktur áll með kartöflum og hráu lauksalati. '),
('Þau liggja eins og hráviði um gólfið. '),
('Sem fréttamaður veistu áreiðanlega hvernig svona hrátt band lítur út. '),
('Beyglaðir grænir stólar lágu eins og hráviði út um allt. '),
('Munir, brotnir og óbrotnir, lágu eins og hráviði um alla íbúðina. '),
('Mér er kalt í þessum hráslaga. '),
('Hvergi hafði lekið, en loftið var auðvitað hrátt og staðið. '),
('Og nú stend ég ekki lengur úti, í nepju og hráslaga. '),
('Var þar æði hráslagalegt eftir indælt vorveðrið heima á Fróni. '),
('Það var hráslagakuldi þó skammt væri liðið yfir miðsumar. '),
('Já, þeir eru sjaldnast uppá það hráa, hundarnir nútildags. '),
('Himinninn grúfði yfir með eymdarlegri birtu sem leysti upp kalda, hráslagalega rökkrið. '),
('Dimt var í lofti og blálygnt en veður hrákalt. '),
('Við gáfum honum hráan fisk. '),
('Þar var hrollkalt og hráslagalegt og skíman að ofan sama og engin. '),
('Bak við þau hamaðist áin gegnum myrkrið og ljómaði eins og hrásilki. '),
('Himnaríkisbirtan umhverfis hana gerði hana næstum hráa. '),
('Þetta góðviðri var mikill léttir eftir hráslaga veðurfarsins í Moskvu. '),
('Vorið er rakt og hráslagalegt. '),
('Ég spratt upp í rúminu og hváði felmtruð. '),
('hváir drengurinn eins og hann hafi aldrei heyrt það orð fyrr. '),
('Hallur hváir, en betlarinn réttir fram lófann, meira segir hann ekki kauplaust. '),
('Ha, hváði maðurinn og beit á vörina. '),
('Upptalning Halls er svo stutt að maðurinn hváir í þrígang. '),
('Steingerður hváði en dóttir hennar endurtók ekki orð sín við hana. '),
('Ha, hvái ég og fæ vart dulið gleði mína. '),
('Ég vissi, að þið munduð hvá við því. '),
('Hvásandi helvíti kom með loðnuna á mig. '),
('Hún kemur út úr eldhúsinu og hváir. '),
('Já, hváir hann æstur, en er þetta kannski ekki satt? '),
('Við Stefán talaði hann lágt og blíðlega og Stefán hváði. '),
('Búðarsveinninn stóð og hváði, alveg steinhissa. '),
('Nei, stundi Lilja með hvási eins og undir mikilli pressu. '),
('Ha, hváði ég, þótt ég vissi alveg hvað hún væri að meina. '),
('Ég heyrði þung skref - einn - tveir - og hvásandi rymjanda. '),
('Ha, hvái ég og það gýs upp í mér reiði. '),
('Ha, hváði feitlagna konan og þurrkaði bjórskegg af efri vörinni. '),
('Ha, hváði Herbert og leit á Mjólkurþambarann. '),
('Honum bregður og lítur upp, hváir: '),
('Ha, hváði Skari og starði á hann. '),
('Þarna var stundum dálítið af hveiti, ef allt hafði gengið vel. '),
('Kartaflan skín eins og hveiti á tjörguðu pappaþaki. '),
('Jens hafði fengið sitt og röðin komin að henni, kaffi og hveitibolla. '),
('Voru þar hveitiakrar sjálfsánir og vínviður vaxinn. '),
('Vindurinn hvein napurlega á byggingunni um nætur. '),
('Það hvein í hjólunum á rennihurðunum þegar hún opnaði og lokaði. '),
('Ef þú vilt ekki þessa hveitibollu skal ég borða hana. '),
('Samanborið við það eru ítölsku hveitistönglarnir hreinasta hörmung. '),
('Það hvein í ljáfarinu og grundin dunaði við sláttinn. '),
('Ég keypti lauk og hveitistöngla. '),
('Það hvein í myndavélunum og myndböndin snerust. '),
('Það var uppbúið, sængurfötin úr hveitipokalérefti. '),
('Hann svipti af sér sænginni með hveitipokaverinu. '),
('Um hádegið dró herra Páll fram box með hveitibollum. '),
('Regnið buldi og hvein úti í garðinum.'),
('Ég fer beina leið að stóra leirfatinu þar sem hveitiflatbökurnar eru geymdar. '),
('Í þessum vasa er laukurinn, hveitistönglarnir í hinum. '),
('Hann hvein, hlýr og sefjandi. '),
('Alténd þó hveitibrauðsdagana, sagði læknirinn og gleypti egg í einum bita. '),
('Ef ég ætti hveitilúku skyldirðu sjá hvað ég gerði úr henni. '),
('Herra Pétur réttir mér hveitibökuna sem drýpur af og segir: '),
('Var þangað flutt heim til Þorsteins hveiti og hunang. '),
('Vindurinn hvein að klettabaki, en hér var logn og skjól. '),
('Hvað hef ég að gera með hveiti? '),
('Rétt eftir háttatíma gekk veðrið upp svo hvein á baðstofunni. '),
('Reyndu þá að baka köku úr hveitinu. '),
('Vindurinn hvein í fjallstindinum og gnauðaði við kofaveggina. '),
('Ég gaf honum vatn að drekka og malað hveiti að éta. '),
('Það hvein í myndavélinni hjá Hinriki. '),
('Hveitipokaléreftið er fyrir glugganum, tandurhreint og himnaríkishvítt. '),
('Þau fengu öll heimabakað hveitibrauð. '),
('Hún hnoðaði fætur mína duglega eins og þeir væru hveitibolludeig. '),
('Þetta er pund af hveiti. '),
('Þetta er mjög lítið pund af hveiti. '),
('Þeir hlógu ákafir þegar kötturinn hvæsti brjálaður. '),
('Þau stukku á mig mörg í einu, urrandi og hvæsandi. '),
('Hann hvæsir þegar hann sér okkur. '),
('Hún tók síðasta skrefið til hans og hvæsti framan í hann. '),
('Farðu, hvæsti Borghildur framan í hann. '),
('Ekki vera leiðinlegur, hvæsti Torfi og fór með kaffikönnuna og síðasta tertufatið. '),
('Ég mun ekki þola slíkar athugasemdir lögmanns, hvæsti varastjórinn. '),
('Mér býður við þér, hvæsti hún. '),
('Ég gef skít í hvaðan upplýsingarnar koma, hvæsti hann. '),
('En Barbara var komin alveg til hans og hvæsti milli samanbitinna tannanna: '),
('Þá hvæsti amma á afa, sagði hann alltaf ýta undir útstáelsi stráksins. '),
('Eigandinn greip í upphandlegg mannsins og hvæsti: '),
('Regnið fellur á kolgljáandi malbikið, hvæsir, streymir niðrí ræsin, bunar, fossar. '),
('Uss, hafði mamma hennar hvæst eins höstuglega og henni var unnt. '),
('Magnús hvæsir út á milli tóbaksgulra tannanna. '),
('Þú tókst peningana fíflið þitt, hvæsti Reynir. '),
('Tómas vakti hana, en þegar hún sá andlitið á honum, hvæsti hún: '),
('Þá heyri ég það hvæsa að mér lágt og hatursfullt: '),
('Aldrei, hvæsti hann á milli samanbitinna tannanna. '),
('Nei, það kemur ekki til mála, hvæsti Haraldur. '),
('Hvað er þetta, drengur? hvæsti ég. '),
('Náið í eiginmann minn, hvæsti Pála. '),
('Já, hvæsti Baldur og strauk svitann af enni sér. '),
('Nú er nóg komið, hvæsti kvenmannsrödd. '),
('Tónninn hækkar og verður að ýlfrandi hvæsi. '),
('Þú áttir að keyra eins hratt og þú gætir, hvæsir Lotta. '),
('Nei, hvæsti hún fokreið og var nóg boðið. '),
('Hvæsandi slög vélarinnar héldu áfram. '),
('Þú biður mig að fara, hvæsti hann og var þungt um andardráttinn. '),
('Lygari, hvæsti Erlendur og tók aftur upp farsímann. '),
('Hann tók að hvæsa, og lét skrölta með miklum þyt. '),
('Enginn vill heyra þína skoðun, hvæsir Anna. '),
('Magga hnippti í mig og hvíslaði eða réttara sagt hvæsti.'),
('Hann hvæsti þegar hann sá mig, segir pabbi. '),
('Hann nennir ekki einu sinni að hvæsa þegar hann sér okkur. '),
('Bara ofboðlítið hvæs og síðan geispi. '),
('Í síðasta sinn, hvæsti hann. '),
('Láttu mig í friði, hvæsti hann á milli samanbitinna tannanna. '),
('Hann hvæsir þegar hann sér okkur. '),
('hvæsti Kristján á leiðinni út. '),
('Nei, nei, gerðu það, láttu þetta eiga sig, hvæsti Chantal. '),
('Hann hvæsir bara í hvert sinn sem hann sér okkur. '),
('Haltu þér saman og sestu inn í bílinn, hvæsti hún. '),
('Í sömu svifum heyrði hann hvæs, eins og frá dýri. '),
('Farðu norður og niður, skepnan þín, hvæsti hún titrandi röddu. '),
('Hann virðir mig ekki viðlits, hvæsi ég. '),
('hvæsti hún fremur en hvíslaði. '),
('Rýmið göngin, hvæsti hann í átt að dyrunum. '),
('Lára gekk ógnandi til hans og hvæsti milli samanbitinna tanna: '),
('Ég nota jurtaliti sem ég bý til sjálf, sagði gamla kanínan. '),
('Þau báru fötur, jusu vatni, og vökvuðu hvert einasta eplatré. '),
('Við byrjuðum að ganga rólega en jukum smám saman hraðann. '),
('Voru það mikil tíðindi sem mjög juku á eftirvæntingu mína. '),
('Seyðið bý ég til sjálf úr ýmsum jurtum. '),
('Úr hvaða jurtum er seyðið? '),
('Í fyrstu fórum við hægt en svo jukum við hraðann smám saman. '),
('Drunurnar jukust í höfði mér. '),
('En á miðjum Kaldadal vex ein lítil jurt. '),
('Tárin streymdu í perluleik niður háu kinnbeinin og juku fegurð andlitsins. '),
('Það svíður að horfa á hana, Julie, það svíður í augun. '),
('Okkur tókst að koma mótornum í gang og jusum sem óðir værum. '),
('Síðasta gjöfin var hvítt blóm í jurtapotti. '),
('Ýmsar jurtir stóðu enn með góðu blómi, þar á meðal nokkrar rósanna. '),
('Langir fingurnir voru eins og uppþornaðar og dauðhvítar jurtarætur. '),
('Þá geturðu safnað fyrir mig jurtunum sem ég talaði um, sagði hún. '),
('Finnst þér ódýrara að juða tækin sundur? '),
('Sumar jurtir bötnuðu með aldrinum og kraftur þeirra jókst. '),
('Úlfbrún bleytti blöð jurtarinnar í seyðinu og lagði þau yfir kvið Fjónu. '),
('Eldri borgarar okkar hafa afskaplega gaman af því að nefna jurtirnar. '),
('Hann seldi líka trjábörk og jurtir gegn niðurgangi og magasári. '),
('Fyrst með jurtum og galdri en síðan með oddhvössu járni. '),
('Fölnuð eða rotvarin jurt getur veitt gleði árum saman. '),
('Vill hann jurtate, flóaða mjólk eða vatn? '),
('Hann drakk sitt eigið jurtaseyði sem hann dró úr vasa. '),
('Ég gaf skipun um að manna julluna mína þegar í stað; '),
('Og þessir fundir juku gruninn og gerðu hann að fullvissu.'),
('Hvers konar jurt er það? '),
('Kringum andlit þeirra uxu furðulegustu jurtir.. '),
('Þarna voru jurtir og krydd og meira að segja þurrkaður njóli. '),
('Umgangist þér enga pólitíska áhugamenn? '),
('Get ég nokkurn tíma byrjað að vinna á pósthúsinu svona útlítandi. '),
('Hún snýr við og gengur með mér að pósthúsinu. '),
('Á skipinu voru hjón frá Póllandi. '),
('Ragnar póstur er ekki einu sinni búinn að svíkja þau! '),
('Hún skildi eftir auða reiti fyrir fæðingarár, lögheimili og póstnúmer. '),
('Róbert hugðist senda vinkonu sinni kort með pósti. '),
('Og samt er pósturinn bara borinn út einusinni á laugardögum. '),
('Um nóttina símaði Hannes Jónsson tvisvar til að ræða við mig póstmál. '),
('Þú átt marga góða vini á póstinum. '),
('Nei, póststofan hefur sýnt sitt rétta eðli. '),
('Mamma sendi mér póstkort frá Svíþjóð. '),
('En pólitískt ofstæki, skriffinnska og formþrælkun fóru með sigur af hólmi. '),
('Lögregluþjónum og póstmönnum var líka oft ruglað saman, svo þú sérð muninn. '),
('Svo hitum við okkur kaffi í fyrramálið og tökum pólhæðina. '),
('Hinsvegar var mér tjáð að hann svaraði ekki pólitískum spurningum munnlega. '),
('Hann var með hreint pókerandlit. '),
('Nei, en það sést á póstkortum, sagði hún. '),
('Hann hafði sent umboð sitt í pósti. '),
('Það er nafn handa glæpamönnum og pólitíkusum. '),
('Pólitíkusarnir fóru og hrópuðu gleðileg jól! '),
('Já, satt er það, en hvað kemur það pólitískum föngum við! '),
('Pólverjinn blótaði hroðalega og gekk burtu. '),
('Við höfðum skóla, pósthús, sveitabúð. '),
('Og ekkert að gerast í pólitíkinni. '),
('Já, kannski eitt Prins Póló líka, svaraði ég. '),
('Það einkennist ekki af pólitísku vali, heldur af myndum, myndhverfingum og orðaforða. '),
('Hókus pókus, nú eru allir draugarnir farnir. '),
('Metnaðurinn bar hann jafnvel yfir pólitískar línur tímans: '),
('Þó svo að hann hafi lent röngum megin í pólitík. '),
('En þú, hvernig komst þú sjálf hjá því að lenda í pólitík? '),
('Ríkisbubbar og pólitíkusar eru hans menn. '),
('Ég komst að fyrstu pólitísku niðurstöðu ævi minnar: '),
('Við tökum mið af Pólstjörnunni, fullyrti ég. '),
('Pólitísk átök tímans lituðu vatnið svart. '),
('Reynir vill koma höggi á pólitíska andstæðinga. '),
('Ég skal kaupa það og senda þér í pósti. '),
('Unga fólkið vill raunhæfar umbætur, opnara þjóðfélag, heilbrigðari og heiðarlegri pólitík. '),
('Hans hagsmunir eru bundnir við pólitíska samherja og vini, jafnvel fjárhagslegan ábata. '),
('Þeir eru alls ekki í pólitískum erindagjörðum; '),
('Hann sá Póllandsferjuna sigla inn til hafnar. '),
('Hann sagðist ætla að senda þá í pósti. '),
('Næsta dag fann hún umslag með sömu ókunnu rithöndinni í póstkassanum. '),
('Í stað pólitískrar sjónskekkju hlaut ég listræna skarpskyggni. '),
('Mér skildist að í pólitísku tilliti hefðu langflestar verið anarkistar. '),
('Ég var að segja að ég hlustaði ekki á pólitíska speki! '),
('Hann skoðaði myndina, póststimpilinn og frímerkið. '),
('Enginn þekkti Síríus, enginn Blástjörnuna, enginn Pólstjörnuna, enginn Karlsvagninn. '),
('Orðið menningarviti var þá skammaryrði í pólítísku tungumáli. '),
('Hefur nokkur spurt hvaða pólitískum flokki þú tilheyrir? '),
('Engu að síður er sú ástæða í samræmi við ákveðna pólitíska stefnu. '),
('Karlarnir eru að tala um pólitík. '),
('Bíllinn slóst utan í grindverk, braut nokkra póstkassa og nam svo staðar. '),
('Ég tengi enn kók og prins póló við afa og skemmtilegu sunnudagsbíltúrana. '),
('Pakkinn kom inn á prentstofu og póststofu varnarmálaskrifstofunnar, var skráður og flokkaður. '),
('Hún hafði útsendara í öllum landsfjórðungum, og fékk þunga pakka með póstinum. '),
('Dagur gekk til vinstri, meðfram Búnaðarbankanum og heim að fangelsinu við Pósthússtræti. '),
('Ég setti bréfin í póst eftir hádegi í dag. '),
('Þar beygði hann og gekk Pósthússtrætið að Austurstræti. '),
('Ég hélt að ef pósturinn breyttist þá breyttist allt. '),
('Þeir voru að reyna að hafa pólitísk áhrif. '),
('Daginn eftir kemur skeytið í pósti. '),
('Auðvitað er nafn staðarins á póststimplinum. '),
('Símskeyti númer tvö er í póstkassanum daginn eftir. '),
('Ég beið komu póstsins með sömu óþreyju og nýliðarnir. '),
('Stór hópur nýliða beið hérumbil aldrei komu póstsins. '),
('Það var póstkassi við smábátahöfnina rétt hjá. '),
('Póllandsferja var á leiðinni inn í höfnina. '),
('Fékkstu póstinn sem ég sendi? '),
('Hann veit allt um pólitík og fjármál. '),
('Þannig fer tæringin með mann, segja strákarnir á pósthúsinu. '),
('Það er útbreiddur misskilningur að þeir beiti einungis pólitíska andstæðinga sína ofsóknum. '),
('Ég vissi ekki að pósturinn væri svona fljótur á leiðinni. '),
('Sérstaklega ef pósturinn kom á meðan pabbi var ekki heima. '),
('Þó gat hann bent á Karlsvagninn, Sjöstirnið og Pólstjörnuna. '),
('Ekki gat hann hjálpað pólitískum föngum, en hann gat gert Teresu hamingjusama. '),
('Ég þoli ekki að hlusta á pólitískt kjaftæði. '),
('Ég held kjafti og geng að póstkössum á einum veggnum. '),
('Eru þetta einhver pólitísk gögn? '),
('Ekki nefna það við hana að þetta tengist pólitík á nokkurn hátt. '),
('Hvað er að frétta af póstmeistaranum? '),
('Pósturinn færði mér fræ efasemdanna. '),
('Umrædd tegund hefur verið framleidd í Suður-Póllandi undanfarin þrjú ár. '),
('Starfsfólk pósthússins hefur ekki einu sinni aðgang að þessu herbergi. '),
('Hvaða ábyrgð ber pósturinn í svona tilfellum? '),
('Ég var farinn að ímynda mér að þeir körpuðu um pólitík. '),
('Daginn eftir fór ég að póstleggja bréfið. '),
('Bak við tjöldin hefur Andri farið með veigamikil hlutverk í pólitískum leikfléttum. '),
('Ég geng sem sagt enn með svona siðspillta pólitíska lágkúru í brjóstinu. '),
('Jafnframt hinum pólitísku hræringum hafði mikil upplýsingatæknibylting gengið yfir heiminn. '),
('Pabbi kom og spurði um póstinn. '),
('Það var miði í póstkassanum. '),
('Móðir þeirra var pólsk og hafði lengi búið í Grikklandi. '),
('Ég póstlegg öll þessi bréf á morgun. '),
('Faðir hans var pólskur greifi en móðirin var ljósmóðir. '),
('Fjölskyldur hér og þar við stíginn fá póstávísanir frá feðrunum í Englandi. '),
('Ég skal senda þér hann aftur með póstinum. '),
('Var þér virkilega leyft að opna póstinn hennar? '),
('En var ræðan nokkuð annað en innantóm pólitísk mælskulist? '),
('Póstlagt og áritað umslag, snyrtilega opnað en bréflaust. '),
('Einn sendillinn segir okkur að hann skuli spyrjast fyrir á pósthúsinu. '),
('Hann vísar ásökunum um pólitískan þrýsting á bug. '),
('Þessi pólitíski fundur var ekki síður fjöldahátíð. '),
('Ég skal senda póstinn til þín á eftir. '),
('Hann ætlar að kæra mig á pósthúsinu. '),
('Engin furða þótt pólitískar ræður Ragnars féllu í grýttan jarðveg. '),
('Land mitt hefur mikilla pólitískra hagsmuna að gæta á þessu svæði. '),
('Sveinn fórst með pólsku skipi í stríðinu. '),
('Þeir sem voru tveim árum á undan voru allir í pólitík. '),
('Einkum skal athuga stöðu pólitískt skipaðra stjórnarnefnda í opinberum stofnunum og fyrirtækjum. '),
('Pósturinn er farinn hér upp frá. '),
('Ég skal setja þetta í póst fyrir þig, mamma, sagði hún. '),
('Hún lagði bréfið í póstkassann við húsgaflinn og Guð var með henni. '),
('Það var eins og hún væri nýkomin úr pólflugi. '),
('Ennfremur spann hann upp pólitísk klögumál sem enga stoð áttu í veruleikanum. '),
('Annars tókum við mið af Pólstjörnunni. '),
('Þeir komu auga á póstbáta sigla sína leið samkvæmt áætlun.'),
('Vinkona mín sendi mér einu sinni póstkort þaðan. '),
('Hilma skrifaði undir og póstlagði bréfið daginn eftir. '),
('Sú hugmynd að skrifa sendibréf var heillaráð frá vini hennar póstmanninum. '),
('Óhjákvæmilegur dráttur vegna póstsamgangna framlengdi óvissuna um nokkra mánuði. '),
('Mamma sárbænir pósthúsið að taka mig aftur. '),
('Hann stígur ekki fæti inn á pósthúsið framar. '),
('Því næst fór hann niður á veg til að gá að póstinum. '),
('Þú yrðir póstur undir eins og stoð og stytta aumingja móður þinnar. '),
('Er í einhverjum frægum skóla í Póllandi. '),
('Ég heyrði að þú ætlaðir að taka þetta próf fyrir pósthúsið? '),
('Segðu skipstjóranum að við séum með eitthvað af póstinum hans hérna. '),
('En maður frá pósthúsinu, hlaut það ekki að vera fínn maður? '),
('Ertu búinn að fara á pósthúsið? '),
('Jörðin er ekki sokkin í einhver djúp, hún hefur ekki haft pólskipti. '),
('Það er engin pólitík í okkar fjölskyldu. '),
('Ég var satt að segja alinn upp í sérkennilegu pólitísku andrúmslofti. '),
('Ég hafði líka séð hann á orlofsdeild póststofunnar. '),
('Ég keypti póstkort og frímerki til að senda móður minni. '),
('Þetta var í póstkassanum í morgun. '),
('Með ómennsku átaki tekst mér að halda puttunum frá þessu litríka silkipúðri. '),
('Þetta pukurástand var að gera mig brjálaða. '),
('Hvenær hætti ég að nenna að punta mig? '),
('Það er líka ánægjulegasti punkturinn í þessu öllu. '),
('Ég finn strax að ég get hreyft alla puttana. '),
('En það kostar puð og stálvilja. '),
('Sum svæðin litu út eins og eftir eldgos í Putalandi. '),
('Síðan hringsnerist hún eins og brjáluð á punktinum. '),
('Purpurarauð smáský léku um vestur og norðurloftið. '),
('Konan sem leiddi grúppuna sagði að þetta væri fróðlegur punktur. '),
('Er það ekki hálft pund? '),
('Hann sleikti puttann og sagði: '),
('Anna punktaði hjá sér og fékk ónot í magann. '),
('Hvergi í heiminum var jafn mikið innihald samankomið í einum punkti. '),
('Láttu reyna á hvað hann þolir, finndu veiku punktana. '),
('Skelfilegt puð held ég verði að paufast upp brekkurnar, sagði Barði. '),
('Anna punktaði niður og beið þegjandi. '),
('Þarna eru kassar fullir af flöskum með purpurarauðri hárolíu. '),
('Eftir langt puð kom orðsending. '),
('Sveinn stóð uppi við klettinn og stangaði með puntstrá úr tönnunum. '),
('Þetta er mjög áhugavert, segi ég og hætti að punkta hjá mér. '),
('Ég borga leigubílstjóranum í rauðum pundum. '),
('Nótt sem nýtan dag, einlægt að puða. '),
('Ég kveiki á grillinu og set nokkrar pulsur á það. '),
('Hún sagðist geta tínt hundrað pund af baðmull á dag. '),
('Það er eins og að setja punkt aftan við sögu, sagði hann. '),
('Skonnortan vaggaði úti á purpurarauðum sjónum með stórsegl og klýfi uppi; '),
('Einn pukurfundur nægir mér í bili! '),
('Ólafur horfði beint fram fyrir sig á ósýnilegan punkt í tímanum. '),
('Pu, sagði gamla konan fyrirlitlega. '),
('Puð sem hefur á manni verið. '),
('Þá kveikti mamma í bréfinu í arninum og faldi pundin. '),
('Óli pulsa var fertugur og svona hafði fertugsafmælið liðið. '),
('Mér leist svo á að þær væru að pukra. '),
('Að hverju ert þú að hlæja, puntudúkkan þín? '),
('Andrés dró annað augað í pung. '),
('Hann tók ekki puttann af hnappinum. '),
('Þeir réðust örvita að honum og punduðu á hann grjóti. '),
('Mennirnir punktuðu niður, aðalritstjórinn hlustaði og sneri baki í borðið. '),
('Ég tek fjörutíu af hundrað pundunum í kistlinum og kladdann. '),
('Hann faldi puttana svo hún sæi ekki hvað hann var að gera. '),
('Lengst úti í sólkerfinu er lítill punktur. '),
('Ekki skera þig í puttana. '),
('Hann hefur enga ráðdeild og kann ekki að ávaxta sitt pund. '),
('Sá kann, trúi ég, að ávaxta sitt pund! '),
('Hann hafði árangurslaust reynt að finna veikan punkt á Jónasi. '),
('Já, ég var allan tímann á Pulitzer. '),
('Textinn var örsmár og illlæsilegur, á ekki stærra letri en sjö punktum. '),
('Fínir nýir punktar í þessari frétt. '),
('Já, við höfum reyndar látið þá hafa nokkra punkta fyrir rannsóknina. '),
('Ókei, sagði Anna og punktaði í blokkina sína. '),
('Marteinn þurrkaði svita framan úr sér og Stefán sleit puntstrá. '),
('Það var puðað, stritað, hlegið og dælan látin ganga. '),
('Má ekki bara hafa pulsur? '),
('Nei, tíu puttar upp á það. '),
('Erna kom við veikan punkt hjá mér og hún vissi það. '),
('Ég sinnti bara starfi mínu sem lögreglumaður, punktur! '),
('Það hlýtur að hafa verið puð. '),
('Hinar konurnar punda á hana spurningum: '),
('Já, er það ekki, sagði hann og rétti mér pumpuna. '),
('Þetta endar allt í einum punkti. '),
('Pabbi, pabbi, þessi fimm pund eru handa nýja barninu. '),
('Pugliese, sagði De Luca, þú veist það. '),
('Þú finnur aldrei neinn veikan punkt hjá mér. '),
('Það voru pulsur í matinn. '),
('Ég punkta hjá mér þær orðsendingar sem máli skipta. '),
('Hann fann lyktarmun á SS og Goða-pulsum. '),
('Bergþóra var að pæla í því hvort þú yrðir einn. '),
('Gemsinn truflar þessar pælingar mínar. '),
('Okkur fannst við vera algerar pæjur. '),
('Ég hef pínt mig til að pæla í gegnum nóttina. '),
('Hvað varst þú að pæla? '),
('Hann var ekkert að pæla í þessu. '),
('Það var eins og hann væri ekki að pæla í neinu. '),
('Ég skil ekki hvað þú ert að pæla. '),
('Ef eitthvað gat truflað menn við akstur voru það pælingar um dauðann. '),
('Hann pælir ekkert í því. '),
('Hvað er það sem þú ert að pæla í? '),
('En þú skalt ekki vera að pæla í því. '),
('Við erum búin að pæla í þessu öllu. '),
('Mér líður vel og ég nenni ekkert að pæla meira í því. '),
('Hann pældi stundum í því hvernig hann myndi haga sér í stríði. '),
('Ég læt hann ekki trufla þessar nýju pælingar mínar. '),
('Ég get ráðið mér mikið sjálf, pæli oft fyrir sjálfa mig. '),
('Fólk hlýtur að pæla í því svona á upphafsstigum sambanda. '),
('Hefurðu einhvern tíma pælt í því? '),
('Ég pæli stundum í því að hætta. '),
('Smátt og smátt hættir maður að pæla í því. '),
('Svona var mikil pæling í öllu á hælinu. '),
('Pælir í því hvað hún myndi gera ef hann segði henni upp. '),
('Eftir London ákvað ég að leggja þær pælingar á hilluna. '),
('Það er vonlaust að lesa úr svipnum hvað hann er að pæla. '),
('Hún pælir í því hvort hún eigi að hringja inn óskalag. '),
('Ég hef allt annað að gera þessa stundina en pæla í því. '),
('Það var ilmur af heitu súkkulaði og pönnukökum. '),
('Múgurinn á pöllunum var staðinn á fætur, hver einasti maður. '),
('Geirlaug kemur inn með fleiri pönnukökur og brosir sem fyrr. '),
('Ég er með pönnu yfir eldinum. '),
('Menn og konur stigu út og héldu á pökkum í fanginu. '),
('Dagblöðum og tímaritum hefur verið staflað í pökkum meðfram veggnum við brautarpallinn. '),
('Pörin tvö voru einungis spegilmyndir hvort annars. '),
('Þar pöntuðu þau sér sitt hvort herbergið. '),
('Þetta merkir að maturinn komi til neytandans tilbúinn á pönnuna. '),
('Enn skarkaði ekki í pönnunum, hnífurinn skyldi enn einn hring í sárinu. '),
('Þeim þótti hann latur og baldinn og pöróttur. '),
('Halldóra fölnaði þegar hún sá hvað var á pöllunum. '),
('Hann fór inn á pöbb og fékk sér bjór. '),
('Utar á heiðinni eru vötnin mörgu, full af silungi og pöddum. '),
('Við pökkuðum niður í flýti og héldum út í myrkur og óvissu. '),
('Mundu bara að hafa deigið nógu þunnt, annars verða pönnukökurnar of þykkar. '),
('Með náköldum fingrum seilist ég í volgar pönnukökur. '),
('Leifunum pökkuðu þær inn í bréf og tóku með sér. '),
('Sveinbjörn horfði á pottana og pönnurnar og hugsaði um mömmu sína. '),
('Nú skal ég kveikja á pönnuskömminni og lýsa ykkur. '),
('Á eftir kom ég við á pöbb og fékk mér einn bjór. '),
('En ég fer mjög sjaldan á pöbb. '),
('Setta rak upp skelfingaróp og missti niður pönnuna. '),
('Umhverfis standa pör og hópar með glösin á lofti. '),
('Ég get varla bakað pönnukökur lengur. '),
('Við pössum upp á þig. '),
('Hann fór fram í eldhús og fékk sér eina pönnuköku í viðbót. '),
('Við pökkum niður vistum áður en við höldum á fjallið. '),
('Hún hafði skrúfað frá gasinu og skellt pönnu á helluna. '),
('Íbúðin var pökkuð af krökkum: '),
('Þetta líkist pönnuköku sem er borin upp að lampa. '),
('Upprúllaðar pönnukökur með sykri var það besta sem ég fékk. '),
('Eru pönnukökur borðaðar í París? '),
('Þar eru pönnukökurnar öðruvísi, flýtti ég mér að segja. '),
('Hún var líka böðuð í kókosfeiti og pökkuð inn í plast. '),
('Út frá pöllum á alþýða að sitja. '),
('Menn hans höfðu upplýst hann um pottana og pönnurnar. '),
('Þeir pöntuðu sér krabba og drukku ölkelduvatn. '),
('Jafnfallega pöddu hafði hann aldrei séð. '),
('Við Dagur og félagar okkar pöntum aðra umferð af stórum bjórum. '),
('Pökkum saman, ég er orðin hundleið á þessu hellalífi. '),
('Þrjú pör fæ ég handa krökkunum mínum. '),
('Ég var svo heppinn að fá flíkur sem pössuðu nokkurn veginn. '),
('Meira að segja stígvélin pössuðu nokkurn veginn. '),
('Fjögur eða fimm pör voru að dansa. '),
('Foreldrarnir pöntuðu sér kaffi, en krakkarnir vildu kók og einhverja köku. '),
('Allt það sem var klístrað fast við pönnuna tilheyrði mér. '),
('Vinstra megin við mig sitja tvö pör. '),
('Ég var að horfa hér á pöddur gegnum gervihnött. '),
('Sumt í henni myndi segja sannleikann um þær pöddur sem við erum. '),
('Þjónninn var kominn aftur, reiðubúinn að taka við pöntun. '),
('Móðir mín stóð raulandi við eldavélina, og kjötið snarkaði á pönnunni. '),
('Pabbi, á ég að segja ömmu að baka pönnukökur? '),
('Ég ætla að fara og segja henni að baka pönnukökur! '),
('Við eigum pöntuð herbergi á Grand Hotel. '),
('Já, við hringdum suður og pöntuðum, sagði Aron. '),
('Skömmu seinna kom húsfreyjan inn með heitar pönnukökur handa gestunum. '),
('Það eru ekki nema örfáir kílómetrar eftir. '),
('Steingrái folinn stóð eftir á hlaðinu. '),
('Mér skilst að félagaskráin sé sérstaklega viðkvæm. '),
('Nú var aðeins grunn Hjaltadalsáin eftir og þaðan var stutt í Enni. '),
('Meðal hátíðargesta sem ég kynntist allnáið í öndverðu voru þrír Svíar. '),
('Þetta síðsumar voru leigjendur Guðmundu óvenjufáir. '),
('Örfáir menn fyrir utan sjálfa meðlimi sveitarinnar. '),
('Örfáir þeirra fengu þó að berjast þar til Katalónía féll. '),
('Dagskráin var mikil og fjölbreytileg. '),
('Stjórnarskráin og helstu leikreglur samfélagsins verða numin úr gildi. '),
('Eitthvað hafði dagskráin breyst því nú var Bárður kynntur á svið. '),
('Um vorið voru þeir orðnir ófleygir og fjólubláir af öllum fúkkalyfjunum. '),
('Ófáir yfirmenn á bestu kaupskipunum eru frá þessum griðastöðum friðsældar og guðhræðslu. '),
('Aðeins örfáir hneyksluðust, en enginn sagði upp áskrift. '),
('Rennslétt ísgljáin lá fyrir framan. '),
('Snorri var vitrastur maður á Íslandi þeirra er eigi voru forspáir. '),
('Aðeins örfáir eru á ferli á götunum. '),
('Sá steingrái var sveittur, frísaði og krafsaði upp moldina. '),
('Myndbandaskráin kemur að takmörkuðu gagni. '),
('Því átti ég eftir að kynnast allnáið. '),
('Rithöfundarþráin liggur líklega ofar hjá þér en guðfræðin. '),
('Sjáðu líka hvað kennsluskráin er orðin spennandi í átta ára bekk! '),
('Kjarnorkuspreingjan afmáir borgir en ekki landafræði; '),
('Og þessi steingrái blær á húðinni eins og jafnan á rauðbirknum mönnum. '),
('Helsjúkur og í hálfgerðu dauðadái komst hann þó heim til sín. '),
('Og það var ævintýraþráin sem gerði hann að byltingarmanni. '),
('Nokkru austar streymdi Fjarðaráin, með djúpum hyljum. '),
('Neðan við hana var jökuláin lygn og breið. '),
('Það eru ekki nema örfáir menn sem hafa séð þetta. '),
('Hvenær er maður á nástrái? '),
('Til allrar lukku voru sárafáir bílar á eynni. '),
('Svaka eru þeir dökkgráir í dag. '),
('Alls staðar blöstu við risastórir sjónvarpsskjáir. '),
('Og þeir verða ófáir sem vilja hjálpa þér til. '),
('Steinarnir eru fölbláir og næstum sjálflýsandi í hvítu umhverfi sínu. '),
('Þangað hafa aðeins örfáir menn komið. '),
('Einar minn, vinningaskráin verður birt síðar. '),
('Erfðaskráin gildir, sagði Gísli stuttur í spuna. '),
('Á skápbotninum hvíla kolbláir lakkskór. '),
('Dagskráin hljóðaði nú á þessa leið: '),
('Ég er á báðum áttum, gríp í seinasta hálmstráið. '),
('Anni lítur aftur á sjónvarpsskjáinn og það er búið. '),
('Þyrftu ekki allir að vera opinskáir hverjir við aðra? '),
('Hann andvarpaði og greip síðasta hálmstráið: '),
('Vorum við aðeins örfáir farþegar í þessum stóra farkosti. '),
('Þetta er allt ein og sama andráin. '),
('Hann klippti tré, reytti arfa og sló puntstráin með orfi. '),
('Og samt var glampinn heitur í stálgráum mistruðum augum henni. '),
('Bakgrunnurinn var sólarlag í bleikum, bláum og fjólubláum litum. '),
('Eitt af dökkbláu ljónunum okkar þremur á gullna grunninum. '),
('Hún var í dökkgráum kjól, lögðum skrautböndum utan um hálsmálið. '),
('Skáldið var kvatt með virktum og verðskuldaðri aðdáun. '),
('Hann var í dökkbláum hlífðarslopp og með hvíta húfu með svörtu deri. '),
('Þegar þeir komu út á hann fór að rigna, örfáum dropum. '),
('Hún steig eitt skref afturábak og horfði á hann af ýktri aðdáun: '),
('Um vorið, örfáum vikum fyrir ferminguna, ákvað ég að strjúka að heiman. '),
('Örfáum mánuðum síðar fórum við tilbaka yfir fljótið í leiftursókn. '),
('Hafirðu ætlað þér að vekja aðdáun okkar þá tókst þér það. '),
('Þú ert sannur karlmaður, tautaði hann fullur aðdáunar. '),
('Á það var letrað fjólubláu bleki og prentstöfum: '),
('Bráðasótt sækti að fólki og gerði útaf við það á örfáum dögum. '),
('Hún horfði bara aðdáunaraugum á hann. '),
('Júlídagurinn var hlýr, en við samt allir í uppháum sokkum við stuttbuxurnar. '),
('Einar minn, sagði hann og horfði á mig ljósbláum augum. '),
('Hann er í ljósgráum ristahlífum og steikarbrúnum skóm. '),
('Ásta lítur upp og horfir á mig þessum djúpbláu augum. '),
('Glugginn var með fjórum dvergsmáum rúðum og var alveg uppi undir loftinu. '),
('Lakið var skreytt litlum fjólubláum blómum. '),
('Ég gat mig hvergi hrært fyrir aðdáun. '),
('Biskupinn var ekki reiðubúinn að fórna nema örfáum sinna manna. '),
('Öll vörpuðu þau frá sér djúpbláum heillandi skuggum. '),
('Hann settist við borðið sem var lagt fölbláum líndúk. '),
('Úr dumbgráu loftinu féllu stórir regndropar niður í svaðið fyrir utan gluggana. '),
('Hún gaf aðdáun sína í skyn með augnaráðinu. '),
('Dýrðarljóminn stóð úr augum hennar og baðaði mig aðdáun. '),
('Hildur horfði full aðdáunar á fima fingur Önnu. '),
('Hann skellti himinbláu bílhurðinni aftur. '),
('Eldri krakkarnir voru alltaf í svörtum eða dökkbláum úlpum. '),
('Hefurðu tekið eftir að hún horfi á mig aðdáunaraugum eða eitthvað svoleiðis? '),
('Og hún hélt á dálítilli festi úr ljósbláum vatnstærum perlum í hendinni. '),
('Hún reis á fætur og fór úr hælaháum skónum. '),
('Sú fregn vakti bæði undrun og aðdáun. '),
('Hannes blæs grábláum reyk beint upp í loftið. '),
('Með örfáum undantekningum tóku samstarfsmennirnir nýliðanum af miklu fálæti. '),
('Hann tekur eftir hvítgráum snjónum á skjánum. '),
('Hann hafði farið úr ljósbláu skyrtunni og var kominn í aðra gula. '),
('Hún er í dökkbláum jakka, bláum gallabuxum og hvítri blússu. '),
('Vínviðurinn svignaði undan fjólubláum og grænum berjum. '),
('Hún fengi jafnvel ekki frið í ellinni fyrir fordómum og aðdáun. '),
('Sterkastan svip á bæjarbraginn settu drifhvítar kirkjur sem flestar skörtuðu heiðbláum hvolfþökum. '),
('Hann horfði á drenginn aðdáunaraugum og klappaði honum á kollinn. '),
('Þarna voru um tuttugu ungir strákar, flestir í dökkbláum sportfötum. '),
('Húsin væru byggð úr ljósrauðum, gulum, bláum, appelsínugulum, svörtum eða silfurgráum steini. '),
('Hann horfði á mig í furðu og aðdáun. '),
('Ég sé út undan mér að árásarmaðurinn er í dökkbláum samfestingi. '),
('Þessi gripur verður til aðdáunar um margar aldir. '),
('Maður í dökkgráum frakka og með marðarskinnshúfu gekk inn fyrir. '),
('Aðdáunin heyrist í hvert sinn sem þú nefnir nafnið hans. '),
('Hann hélt á dökkbláum borða í annarri hendinni. '),
('Litirnir breyttust úr ljósbláum í himinbláan og fjólubláan og grængylltan. '),
('Þessar örsmáu verur líta út einsog halakörtur. '),
('Ljósmyndarinn var í ljósgráum ullarfrakka, blankskóm og jakkafötum. '),
('Stökk hans á þessari stöng vöktu aðdáun hvers manns. '),
('Sá fremsti ríður á ljósgráum hesti stórum, og er hár í söðli. '),
('Elsa er í síðum fjólubláum kjól með dumbrauðum strokum eftir honum endilöngum. '),
('Aðdáunin skein af krímugu andlitinu, gegnum hið óburstaða skegg. '),
('Allt umhverfis voru dimmblá og mórauð fjöll undir heiðbláum himni. '),
('Ólafur gengur fram og aftur þessa örfáu fermetra. '),
('Óbeit og aðdáun toguðust á um mig. '),
('Engin stúlka í þessum landshluta hafði kynnst annarri eins aðdáun. '),
('Skynjun mín hafði skerpst á örfáum andartökum. '),
('Þessir örfáu dagar sem eru eins og ókeypis á Íslandi. '),
('Hann kom á staðinn örfáum mínútum á undan þér. '),
('Matti hefur líklega setið í þessum sama stól fyrir aðeins örfáum dögum. '),
('Vesalings agnarsmáu fæturnir að þurfa að bera þetta hlass! '),
('Hún sá að þau voru hrædd, en líka óttablandna aðdáunina. '),
('Ég keypti hana sjálf úti í Björnsbakaríi. '),
('Ég vissi að eftir jólafríið byrjaði skólinn aftur. '),
('Hann tók fram tvö glös og hellti viskíi í þau: '),
('Hann lokar reikningnum og partíið er flutt áfram út í kuldann. '),
('Hann hvolfdi í sig því sem eftir var af viskíinu. '),
('Ég gerði hlé á sumarfríinu mínu til að vera til taks. '),
('Helltirðu á hana brennivíni í fylliríinu? '),
('Að harmleiknum loknum fóru allir heim, partíið gjörónýtt. '),
('Viskíið hennar Anni er ekki gott. '),
('Henni varð enn þyngra um andardrátt, tyggigúmmíið þandist í munninum. '),
('Hún læsti salernisdyrunum á eftir sér og henti tyggigúmmíinu í ruslakörfuna. '),
('Mér ferst ekki, hvorki að býsnast yfir fylliríi né barnauppeldi. '),
('Svínaríi kommúnista getur einginn lýst með orðum, sagði hún. '),
('Hann langaði greinilega að vera í þessu partíi þar sem allir voru. '),
('Skólinn var í verkfalli og hann var í framlengdu jólafríi. '),
('- Hvers vegna hefurðu þá gert hlé á sumarfríinu þínu? '),
('Hann fann hitt bakaríið sem var til vinstri frá torginu. '),
('Mér heyrist þú fara á kostum eftir fylliríið í nótt, sagði hún. '),
('Loks komst hann ekki upp brekkuna hjá bakaríinu. '),
('Hann stóð við bakaríið og studdi sig við gluggapóstinn. '),
('Síðan fór hún inn í bakaríið. '),
('Allur þessi fjöldi hittist í gríðarstóru sumarhúsi í sumarfríinu. '),
('Partíið er líka búið, sagði Sara, það eru allir að fara út. '),
('Staðurinn er lítið hótel uppi í fjöllum og hann er í sumarfríi. '),
('Já, segir Grímur, ég kynntist henni í sumarfríinu. '),
('Maður verður þá alltaf í sumarfríi. '),
('Vertu aðeins lengur, sumarfríið er ekki búið ennþá. '),
('Batteríið er að verða búið, segir hún þegar ljósið dofnar. '),
('Því slakari sem batteríin urðu, því þéttar þyrptust allir umhverfis útvarpstækið. '),
('Af hverju komstu ekki í partíið hennar Ásdísar? '),
('Hvað gerðuð þið í partíinu? '),
('Ætlið þið þá að fara til Írlands í sumarfríinu? '),
('Ekki að furða þótt þér hafi ekki verið boðið í partíið. '),
('Páll andvarpaði og sneri stórum vöndli af spaghettíi um gaffalinn. '),
('Þú blandar rifnum eplum saman við jógúrt og góðan slurk af karríi. '),
('Síðan hitaði hann vírþráð yfir eldi þar til vírinn var rauðglóandi. '),
('Ef hún flýði, gætu eskimóarnir auðveldlega handsamað hana. '),
('Andlit Lólóar breytist í spurningarmerki. '),
('Stjórnleysi og grimmd höfðu gereyðilagt háþróaða kristna menningu. '),
('En það er gaman að horfa á ofninn, svona uppmjóan og háan. '),
('Mamma á að sækja okkur í dag, sagði Kalli mótþróafullur. '),
('Að frátöldum skotbardögum og óróa er sumarloftið þar fullt af sjúkdómum. '),
('Systurnar horfa skilningssljóar á föður sinn. '),
('Úti á miðjum Húnaflóanum datt á með dúnalogn. '),
('Mér finnst þetta fáránlegt þar sem flamingóar hafa aldrei sést á Íslandi. '),
('Ég sá strax hvers kyns var, kannaðist við óróann í Frikka. '),
('Þræðirnir verða smátt og smátt rauðglóandi. '),
('Köngulóarvefurinn raknaði upp á fimm mínútum. '),
('Venjulegur þriggja kílóa kúlufiskur inniheldur nægilegt eitur til að drepa þrjátíu manns. '),
('Úti var kyrt veður, stjörnubjart, frost mikið og alsnjóa. '),
('Hérna átti að reyna áætlunina, endurbæta hana og fullþróa. '),
('Finnur svaraði engu og sýndi engan mótþróa. '),
('Vegna einhvers kynlegs óróa hvörfluðu augun stöðugt af sýningartjaldinu. '),
('Hann tók um axlir Birnu Eyglóar. '),
('Hann horfði beint í þykk gleraugu Birnu Eyglóar. '),
('Það var köngurlóarvefur hérna efst í klaufinni. '),
('Kóngulóarvefirnir, leðjan, mosinn og skófirnar flutu burt. '),
('Mamma, sagði hún með greinilegan mótþróa í röddinni. '),
('Og sólin brosir ekki í ljóðum eskimóa. '),
('Í því felst ekkert sem þarf að valda óróa. '),
('Það var í rauninni aðeins tvennt sem olli honum óróa. '),
('Hann var þá innikróaður í veröld þar sem eingöngu var svart fólk. '),
('Hvernig þeim síðarnefnda hafði tekist að lifa af óróatímana veit ég ekki. '),
('Allt gerði þetta umræðuna afskaplega ófrjóa. '),
('Þegar hún lék á píanóið lá við að nefið snerti nóturnar. '),
('Stúlkan kinkaði kolli og litla fólkið í stúdíóinu klappaði fyrir Sveinbirni. '),
('Ég sat eftir í bíóinu. '),
('Þeir blanda einhverjum lyfjum út í kíóið. '),
('Er hægt að hafa svona mikinn áhuga á sjampói? '),
('Ég verð að henda tyggjóinu mínu, sagði hún. '),
('Eitt þeirra var á tónleikunum í Bæjarbíói. '),
('Umhverfis píanóið safnaðist ungviðið og kyrjaði söngva sína. '),
('Hann leit niður á strigaskóinn. '),
('Þau litu bæði eitt örskot niður á tyggjóið í höndum hennar. '),
('Við hefðum kannski betur farið á unglingadiskóið með krökkunum. '),
('Í salnum í Austurbæjarbíói er hvert sæti skipað. '),
('Í mér rótgróinn uggur um að verða fyrir vonbrigðum. '),
('En þessi mótþrói þeirra var ekki til annars en glæða ást þeirra. '),
('Litla sjónvarpið hans með innbyggða vídeóinu gat ekki keppt við það. '),
('Túnin voru algróin og hinir ljósrauðu fíflar orðnir að gráhærðum bifukollum. '),
('Neðan úr kjallara barst þeim daufur ómur frá píanói og fiðlu. '),
('Sjáðu alla gufuna, Marta, þetta er bara eins og í þungarokksvídeói. '),
('Heima yrðu aldrei til peningar fyrir píanói. '),
('Setið var í hverju sæti í Bæjarbíói í Hafnarfirði og kliðurinn mikill. '),
('Ætlarðu ekki að drekka kakóið? bætti hún við. '),
('Vísindin um framþróunina skýra hvað lífið er. '),
('En krían kom sjálf og skógarþrestir og heiðlóur. '),
('Merkasta og friðsamlegasta framþróunin verður alltaf fyrir tilstilli einstaklinga. '),
('Og að auki hafði hann enn bætt á sig þremur kílóum. '),
('Í útvarpinu var lesin hæg og auðveld morgunleikfimi við píanóundirleik. '),
('Estha var í ljósu támjóu skónum og með Elvisbrúskinn. '),
('Í morgun var ég þremur kílóum léttari en í gær. '),
('Skammt frá honum voru fáein lömb afkróuð. '),
('Kannski hafði Erna næstum því fengið stóra vinninginn, munað örmjóu! '),
('Sumir steyttu hnefana upp yfir fjöllin og ógnuðu heiðarbúunum. '),
('Þau horfðu vantrúuð á hana. '),
('Á flokksþinginu var honum fagnað af 1900 nýkjörnum fulltrúum. '),
('Þú ert að grínast, sagði Anna vantrúuð. '),
('Sum blaðanna voru bundin við ákveðin hverfi, önnur ætluð öllum borgarbúum. '),
('Reiðin beinist því að íbúum borgarinnar. '),
('Hún starði á orðið og hristi höfuðið vantrúuð. '),
('Þá var íslenska sendinefndin mætt og samanstóð einkum af fulltrúum stjórnmálaflokkanna. '),
('Afi hallaðist að skoðunum hinna strangtrúuðu að þessu leyti. '),
('Öræfasveit var þá mjög einangruð, óbrúuð stórfljót á báðar hendur. '),
('Þau horfðu á mig vantrúuð en höfðu hvorki önnur ráð né betri. '),
('Mundi hann eftir íbúum í þessu húsi? '),
('Hún horfði vantrúuð á hann. '),
('Þannig stóðu níu samtök að stofnun nefndarinnar ásamt átta einstaklingsfulltrúum. '),
('Lífið á þessum samyrkjubúum mótaðist af samhjálp og sameign allra meðlima. '),
('Ekki höfðu fleiri af kaupstaðarbúum þann umbúnað. '),
('Afi átti sér alla þá náttúrlegu óvini sem fjallabúum eru fyrirbúnir. '),
('Þvílíkur hugsunarháttur virtist vera borgarbúum fullkomlega framandi. '),
('Hún starði á hann vantrúuð, svo hæðnislega og á endanum hló hún. '),
('Fulltrúaráð var skipað skólastjórn og tuttugu öðrum fulltrúum. '),
('Á torginu miðju stendur höggmynd og vakir yfir bæjarbúum. '),
('Var þeim fagnað mjög af bæjarbúum við komuna og ógninni aflétt. '),
('Víðast var þeim samt vel tekið og einstæð reynsla að kynnast úthverfabúum. '),
('Sum þeirra voru auðsæilega fársjúk af sólarleysi og vannæringu. '),
('Hann hafði ekkert innsæi í annað fólk. '),
('Spurningunni er enn ósvarað hvort við þolum raunsæi. '),
('Hlutlægni mín og áhugaleysið hafði auðsæilega hrifið hann. '),
('Kvenlegt innsæi virtist koma fyrir lítið. '),
('Við og við hugsa ég um helgarferðina á litla sveitabæinn. '),
('Furðulegt hvernig hann gat látið andblæinn í ímyndunarafli sínu gagntaka menn. '),
('Innsæið leysti ekkert, hún gat ekki stöðvað grátinn. '),
('Hann réð auðsæilega einn yfir bílnum sem ók eftir duttlungum hans. '),
('Óraunsæi leiðir í ógöngur og endanlega til tortímingar. '),
('Fyrst datt þeim í hug að taka viðtalið við hliðina á bílhræinu. '),
('Enginn sýndist tiltakanlega hrifinn af þessu innsæi hennar. '),
('Hún sá bóndabæina fljúga hjá. '),
('Hann notaði allt í senn, innsæi, staðreyndir og útilokunaraðferð. '),
('Hann ætlaði að sá í það grasfræi. '),
('Fornleifafræðingar töldu þessar rústir bestu fáanlegu heimildir um norræna miðaldabæi. '),
('Kristín litla var auðsæilega hljóðlátt og athugult barn. '),
('Ég veðjaði á innsæið og veröldin breytti um svip. '),
('Rómantík og raunsæi bjuggu í skaphöfn þessa djarfhuga manns. '),
('Það eru nokkrir eyðibæir þar. '),
('Konan var klædd svörtu, auðsæilega sorgarbúningi. '),
('Hún var að hugsa um bóndabæina og beindi orðum sínum til Nínu: '),
('Maður verður að reyna að treysta á tilfinninguna, innsæið. '),
('Ég opna gluggann og finn kvöldblæinn á andliti mínu. '),
('Jóhannes tilkynnti að ég botnaði auðsæilega ekki neitt í neinu. '),
('Við vorum að leggja af stað í Garðabæinn til tengdaforeldra minna. '),
('Enginn var á stjái framan við bóndabæinn. '),
('Raunsæismanneskjan hafði rétt fyrir sér. '),
('Raunsæismálverk hékk á veggnum hægra megin ofan við stórskorið höfuð leynilögreglustjórans. '),
('Þrátt fyrir veikindablæinn á andliti hans brá þar fyrir fagnaðarbjarma. '),
('Með hlutlausum ytri lýsingum veitti hann innsæi í falinn heim. '),
('Einn var rétt utan við miðbæinn, reyndar ekki langt héðan úr Þingholtunum. '),
('Hér stóðst ekkert samanburð við torfbæinn eða kjallarann. '),
('Samtals urðu greinar hans átján, allar markaðar fágætu innsæi og víðtækri þekkingu. '),
('Hún þekkti raddblæinn, hann var við það að bresta í grát. '),
('Hann er með stóra hvíta tösku með ankeri á. '),
('Bankinn byggir fyrir eigið fé. '),
('Ó, Guð, mér þykir fyrir þessu, Frankie. '),
('Ég hélt að flestir rithöfundar væru skítblankir? '),
('Mér tókst með erfiðismunum að opna krana neðst á tankinum. '),
('Frankie ætti ekki að vera á krám, og hún sagði: '),
('Handsprengju hafði verið komið fyrir í bensíntanki bíls hans. '),
('Þeir voru ekki allir staurblankir. '),
('Auglýsingin varð fræg á Íslandi af því Landsbankinn reyndi sömu aðferð. '),
('Ertu enn að hugsa mannkindinni þegjandi þörfina? '),
('Jón gekk meðfram ógnarstórum tanki, gamall beinhákarl fylgdi honum langleiðina. '),
('Bankinn vildi ekki sjá þetta. '),
('Hann kom við á bensínsjálfsala og fyllti tankinn. '),
('Þar eru túristabúðir og banki og það er innangengt þaðan í hótelið. '),
('Bankinn er örugglega með myndavélar. '),
('Þú verður að bíða þangað til Búnaðarbankinn opnar í fyrramálið. '),
('En franski frankinn hafði fallið sem afleiðing verkfalla í tæpan mánuð. '),
('Ég læt þá líta á vélina líka, og fylla tankinn af bensíni. '),
('Ekki gleyma að hringja í píparann út af heitavatnstankinum. '),
('Fjósabuxur úr litlausu nankinefni, ullarbolur, treyja, goltreyja, dökkblá peysa. '),
('Þú átt ekkert í þessu, bankinn á það! '),
('Það sljákkaði í talsmönnum sóknarinnar en sátu samt fast við sinn keip. '),
('Við þetta sljákkaði í hreppstjóranum. '),
('Við það sljákkaði í honum.'),
('Þá sljákkar venjulega í flestum þeim ruddalegustu. '),
('Það sljákkaði dálítið í Borghildi. '),
('Hann sópaði henni varlega fram af skenknum og niður á gólf. '),
('Þarna var skenkur með hekluðum dúk og bjánalegri skál. '),
('Yfir skenknum hangir almanak, útgefið af félaginu. '),
('Við fáum tvö rúm, einn skenk með spegli, borð og tvo stóla. '),
('Og hvaða refsingu myndi hann skenkja honum? '),
('Annar sjódómendanna var skipstjóri á seglskipi, með rauðleitt skegg og guðrækilega þenkjandi. '),
('- en hvað þenkirðu, að sú gamla maddame B. '),
('Síðan skellir hann því á skenkinn svo smellur í og úrskurðar: '),
('Fer jafnvel að skenkja kaffi í bollann minn. '),
('Eigandi skipafélagsins rigsar inn eitt drýgindabros og byrjar að skenkja sér romm. '),
('Neyðarútgangurinn - þarna var hann, til vinstri við skenkinn. '),
('Örvar var of vísindalega þenkjandi til að láta þar við sitja. '),
('Bak við skenkinn, sagði karlinn. '),
('Fer að skenkja kaffi í litla bolla. '),
('Fyrir handan rýkur úr strompi loðnubræðslunnar. '),
('Siggi var orðinn ansi hreint slompaður þegar við gengum til náða. '),
('Hann hafði haft trompásinn uppi í erminni. '),
('Við fundum sitt eintakið af hvorri plötunni hans í kompunni. '),
('Þessir peningar gætu hafa verið í kompunni þegar ráðist var á hann. '),
('Fór hann þá upp á eldhússtrompinn og gægðist inn. '),
('Þau gægðust nú bæði inn um eldhússtrompinn. '),
('Stromphúfan hallaðist fram og Erlendur horfði upp eftir henni. '),
('Hann fór inn í kompuna sem átti að heita vinnuherbergi hans. '),
('Enginn reykur upp af strompi, og engin glæta frá ljósgjafa á skjám. '),
('Þetta með fötin var nýtt, þau gætu trompað því út. '),
('Það rýkur úr strompi býlisins uppfrá. '),
('Hann reykti eins og strompur. '),
('Hann fór í hart og núna erum við þó í þolanlegri kompu. '),
('Grétar var farinn að kíkja í bæinn og kom til baka slompaður. '),
('Á trompetinn spilaði hannn einungis sér til hugarhægðar. '),
('Þú gætir horft á vídeó í kompunni á meðan ég afgreiði. '),
('Var hann með mikið af peningum inni í kompunni hjá sér? '),
('Hangir úlpan ekki í kompunni? '),
('Guðlaugur var með peninga í kompunni. '),
('Hann hafði öll trompin á hendi - eignir, öryggi, völd.'),
('Hann arkar fram og aftur um skrifstofukompu sína, sömu leiðina. '),
('Tuttugu mínútum síðar les Ásbjörn á skjánum inn í kompu hjá sér: '),
('Hann læddi sér inn í kompuna. '),
('Loftið inni í gluggalausri kaffikompunni var mettað af tóbaksreyk, táfýlu og slorlykt. '),
('Hann opnaði minniskompuna sína og blaðaði í henni. '),
('Enginn reykur upp af strompi, og engin glæta frá ljósgjafa á skjám. '),
('Þeir fóru og litu á kompuna. '),
('Hann settist inn í vinnukompu sína og hugsaði. '),
('Þar sá ég hús við stíg með háum strompi. '),
('Þau settust niður í herbergiskompu Guðlaugs. '),
('Kompan minnti hann á fangaklefa. '),
('Reykurinn úr strompunum stóð beint í loft upp og hvarf. '),
('Heimilisfólkið virðist allt vera komplíss í þessu samsæri og gefur ekkert upp. '),
('Og veistu, sagði hún, svo pompuðum við í sjóinn. '),
('Upp af litlum strompi liðaðist reykur. '),
('Það herbergi var notað sem kompa. '),
('Það rýkur upp úr strompinum á gamla reykhúsi Sláturfélagsins. '),
('Skóg kaldra verksmiðjustrompa ber við djúpbláan himin. '),
('Kompan hans Ásbjörns er yfirgengilega snyrtileg. '),
('Húsið stóð eitt, ljóslaust og andvana, fyrir utan þunna reykjarslæðu úr strompinum. '),
('Reykurinn liðast ekki lengur upp um strompinn á húsinu. '),
('Það kom ekki heldur neinn reykur uppúr strompinum. '),
('Um kvöldið sat hún uppi í kompunni og skrifaði Bergi lækni bréf. '),
('Sé þig, sagði Skari og var orðinn slompaður. '),
('Það rauk úr strompinum, og grár reykurinn dreifðist hægt yfir græna laufþekjuna. '),
('Dyrnar að kompunni voru opnar og Erlendur gekk fram á ganginn. '),
('Reykur steig upp úr strompi og ljós kom í glugga. '),
('Hún leit yfir kompuna og kinkaði kolli og stóð upp. '),
('Mér skilst að hann hafi búið í kompunni þarna niðri árum saman. '),
('Tengslin ná lengra aftur en það, sagði móðir mín montin. '),
('Vont var það fyrir en verra er það nú, sagði hann. '),
('Hann montaði sig af því. '),
('Þetta hefur verið svo erfitt og svo vont, svo lengi. '),
('Ég var á verkstæðinu og það var kallað á mig á kontórinn. '),
('Ég gleymdi mér andartak og gerðist montinn. '),
('Finst honum ekki vont að geta ekki lokið upp kirkjunni? '),
('Sum ljóðin komu honum í vont skap. '),
('Ég þekkti strák sem var montinn og spurði: '),
('Núna er hann kominn í grá jakkaföt eins og allir hinir kontóristarnir. '),
('Ég fékk mér sopa, en vatnið var salt og hræðilega bragðvont. '),
('Á leiðinni upp á kontórinn hringir gemsinn. '),
('Ég á orðið vont með að muna, sagði Þorgerður og stundi. '),
('Hún er að reyna að monta sig, hvíslaði Elsa. '),
('Þetta er vont rúgbrauð, segi ég. '),
('Eldsnemma er ég mættur inn á kontór til Hannesar. '),
('Og það sem hann skildi ekki kom honum í vont skap. '),
('Ég átti vont með að ímynda mér hann við þá iðju. '),
('Landróver, Fíat, Lapplander Línkoln Kontínental. '),
('Myrkrið í stofunni hleypti honum skyndilega aftur í vont skap. '),
('Nú er hann einkaspæjari með kontór hér niðri við göngugötuna. '),
('Hann stígur í pontu klukkan tvö. '),
('Ekkert er eins vont og illa reykt kjöt. '),
('Hann vildi ekki hætta á að komast í vont skap. '),
('Það var vont að geta ekki kvatt. '),
('nú er vont að fara að spásséra. '),
('Ég hef heyrt að það sé vont. '),
('Það er vont að missa þig, sagði Andrés. '),
('Ég klöngraðist og átti vont með að halda jafnvæginu. '),
('Rúnar var þreyttur en augsýnilega rígmontinn yfir afreki sínu. '),
('Hann sagði að það væri svaka vont. '),
('Montið í þessum karli, sagði hún, það er óþolandi. '),
('Ég þarf bara að fá mér kontór. '),
('Hvað í ósköpunum ætlar maður eins og þú að gera við kontór? '),
('Ég vildi ekki monta mig. '),
('Montið í skáldinu er ekkert venjulegt mont. '),
('Breiður mannflaumurinn mjókkar skyndilega þegar hann hverfur niður rúllustiga og undir lestarpall. '),
('Auk þess mjókkaði fljótið á þessum stað. '),
('Á afleggjaranum til Bakkagerðis mjókkaði vegurinn og varð holóttari. '),
('Sögur einsog Jói og baunagrasið þótti Ragnari tómt píp.'),
('Á daginn máttu þeir reika um, en lífið var fábreytilegt og innantómt. '),
('Hún starir ofan í tómt glasið. '),
('Þegar þangað kom greip ég enn í tómt. '),
('Eldhúsið var tómt og allt í einu mjög hrörlegt að sjá. '),
('Kexpakkinn enn á borðinu, mylsna um allt borð, og hálftómt mjólkurglas. '),
('Farðu með það, lífið er innantómt. '),
('Hann söng inn á hljómplötu sem skrifað var um í blöðunum. '),
('Tómt þvaður og vitleysa, þessu átti fólk að trúa. '),
('Lífið var ekki annað en tómt þref. '),
('Glasið í hægri hendinni er tómt. '),
('Barnaherbergið var að vísu tómt. '),
('Kotið stendur stundum tómt á sumrin.'),
('Enda grunaði mig að símtalið í morgun væri tómt rugl. '),
('Og margan sumardag var kotið alveg tómt. '),
('Kannski var þetta tómt háð? '),
('Ég held að það hafi verið næstum því tómt. '),
('Nei, glasið var á náttborðinu, tómt. '),
('Svona er lífið - eintómt grín! '),
('Við vorum að ljúka við fyrsta atriðið á dagskránni, stríðshljómkviðuna. '),
('Það var nánast tómt fyrir utan borð og loftljós með sterkri birtu. '),
('Og réðust inn í tjaldið tómt. '),
('Hátíðin hófst um tíuleytið með stuttri guðsþjónustu í dómkirkjunni. '),
('Þegar við komum heim er herbergið tómt. '),
('Höfuðið var einhvern veginn algjörlega tómt. '),
('Hann vildi ekki hafa neitt innantómt hjal. '),
('Glasið hans er tómt aftur. '),
('Þetta var tómt rugl og vitleysa, segi ég. '),
('Höfuð hans var algerlega tómt, ekki ein einasta hugsun eftir. '),
('Hann ætlaði að kippa í Martein en greip í tómt, Marteinn horfinn. '),
('Amma sagði að þetta væri tómt rugl. '),
('Það hafði verið brotið upp og var tómt. '),
('Framstæðir deplóttir blómkólfarnir ævinlega gulir. '),
('Hitt glasið var aftur á móti tómt. '),
('Þar var bunki af gömlum tímaritum sem ég ætlaði að henda. '),
('En í hliðarhellinum vinstra megin heyrðu þeir söng í munkinum. '),
('Hún fer ofan í dunkinn og tekur upp kringlóttar hafrakökur. '),
('Þá ýtir hún dunkinum yfir borðið til hans. '),
('Eftir smástund stendur konan upp og tekur kökudunkinn, setur á hann lokið. '),
('En lögmaður varð eftir hjá munkinum. '),
('Það var sem logaði upp í munkinum. '),
('Í umslaginu er vænn bunki af hundrað dollara seðlum. '),
('Innan í henni er bunki af útprentuðum blöðum. '),
('Tveir hrafnar komu fljúgandi með krunki fram af grasbakkanum ofan við braggana. '),
('Í pokanum var pappírsbunki og á blöðin var skrifað á kínversku. '),
('Á meðan ræddi hann við munkinn um ættbálkastríðið. '),
('Það hlýtur að standa lengi, sagði hann við munkinn. '),
('Það dimmir með hverju krunki. '),
('Þetta er handa þér, sagði hann, og rétti munkinum einn hlutann. '),
('Síðan tók hann fjórða hlutann og fól enn í hendur munkinum. '),
('Í honum var þykkur blaðabunki, festur saman með spotta. '),
('Bunki af samanbrotnum krumpuðum fötum beið straujunar. '),
('Síðan tók við andstyggilegt óbragð í munninum, súrt og fúlt. '),
('Hann stóð fyrir framan mjólkina, ostinn og jógúrtina. '),
('Hann elskaði jógúrt og fann núna hvað hann var svangur. '),
('Skeggið fylltist af jógúrt með litlum jarðarberjabitum. '),
('Hefðu borðað jógúrt á morgnana, eins og ég bað þig um? '),
('Ég er heldur ekkert hrædd við Matta, þann ljóta skúrk. '),
('Vertu sæll, vinur, og gleymdu ekki að kaupa jógúrtina, sagði hún. '),
('Nei, það voru líklega ekki margir sem drukku úr jógúrtdósunum. '),
('Að ég ætti að borða meiri jógúrt, svaraði ég. '),
('Þú selur ekki jógúrt, er það? '),
('Barnið í vagninum horfði bara á þær súrt á svip. '),
('Sú hefur lúrt á skildingunum, kerlan sú arna. '),
('Þetta var einungis til að sýnast, en hann átti einskis annars úrkosta. '),
('Hún lagði teskeiðina á borðið og sleikti síðustu jógúrtleifarnar upp með vísifingri. '),
('Ég spyr hvort hann hafi smakkað fiskpinna með jógúrtsósu. '),
('Ertu kannski með súrtunnu hérna? '),
('Úrkoman hafði aukist og nú var farið að hvessa. '),
('En hann átti ekki annars úrkosta. '),
('Hann dró blaðaúrklippu upp úr brjóstvasanum: '),
('Ég held, að úrkoman sé meiri þar. '),
('Stundum eru þar gúrkur, tómatar og maís. '),
('Þrátt fyrir úrkomuna var útsýni dágott á Selfossi, sem var fyrsti viðkomustaður. '),
('Þunnt skyr er líka gott, ef það er ekki súrt. '),
('Illfært var bæja á milli vegna úrkomu. '),
('Nú benti pabbi á úrklippuna og sagði snjöllum rómi: '),
('Þegar við vorum að taka til rakst hún á blaðaúrklippu: '),
('Hann hélt agúrkunni með báðum loppum rétt einsog hann væri lítið barn. '),
('Veðrið hafði lægt og úrkoman var minni. '),
('Hún fann hvernig súrt og hressandi bragðið kipraði góminn í henni saman. '),
('Við erum öll svefnvana, þreytt og sveitt og orðin úrkula vonar. '),
('Ársæll flettir úrklippum, strikar við, hristir þungt höfuð. '),
('Hann var að spila á píanóið og drekka púrtara. '),
('En á stríðstímum er ekki verið að prútta um smámuni. '),
('Ekki er nú trútt með það. '),
('Samt treysti hann sér ekki að prútta. '),
('Þú getur trútt um talað. '),
('En ég kæri mig ekki um að prútta um neitt. '),
('Hann benti líka á ryðbrúnu seglin á kútterunum og fiskibátunum. '),
('Á bökkum árinnar uxu tré, slúttu angurfull. '),
('Gerðu svo vel, krútt, er sagt á bak við mig. '),
('Hann var algert krútt, bröndóttur með hvíta fætur. '),
('Algjört krútt, segir hún, og lítið á þessar dýrlegu gullnu krullur. '),
('En flösku varð hún að eignast, og túttu! '),
('Nei sko, litlu krúttin, standið þið hér mjálmandi? '),
('Trén slúttu í hallanum ofan við húsið. '),
('Heiðarnar dökknuðu, hagarnir grænkuðu með hverjum líðandi degi. '),
('Raunar var hún yfir sig ánægð með að hafa kynnst þessari frænku. '),
('Þegar langamma dæi mundi hún loks segja bestu frænku að fara. '),
('Þvílíkt og annað eins, frænkan vissi ekki hvenær lýðveldið var stofnað! '),
('Ég hugsaði með mér að besta frænka hefði rangt fyrir sér. '),
('Frænkan skellihló og mamma horfði lengi á hana: '),
('Þá yrðu fleiri til skiptanna fyrir frænkurnar. '),
('Kannski gerði ég það, já, hreytti Selma frænka út úr sér. '),
('Það er ekki það sem hann vildi sjálfur, sagði Selma frænka. '),
('Hann vill ekki fara til Þrándheims, sagði Selma frænka uppgefin. '),
('Maður veit ekki hvað skal gera þegar Gunna frænka segir við mann: '),
('Frænka þeirra kemur á morgun, útskýrði hún fyrir manninum. '),
('Besta frænka þarf að segja þér svolítið, sagði hún við móður sína. '),
('Ruth hafði alltaf viljað að móðir hennar væri líkari Maríu frænku. '),
('Láttu frænkurnar hressa uppá þig, sagði Óskar. '),
('Við kvöldverðarborðið lét besta frænka eins og ég væri aftur orðin hjálparlaus. '),
('En besta frænka sagði mér þetta og hún vissi sínu viti. '),
('Besta frænka gerði við gat á gömlum buxum sem ég átti. '),
('Besta frænka sendi mér hörkulegt augnatillit þegar hún heyrði þetta. '),
('Ég beið þess að besta frænka færi fyrst. '),
('Besta frænka settist umsvifalaust upp og talaði við mig með höndunum. '),
('Besta frænka hafði einu sinni sagt eitthvað svipað. '),
('Halló, Selma frænka, segir Anna. '),
('Hlífðu mér við bullinu í þér, Anna, segir Selma frænka. '),
('Hún vill ekki koma inn til Evu frænku. '),
('Ég mundi samt borga þér þó að ég sé frænka þín. '),
('Það er ekki nóg fyrir Möggu frænku. '),
('Besta frænka var ekki í k  ang. '),
('Þetta er Anna frænka þín hérna! '),
('Hún sagði mér líka hvar ég fyndi bestu frænku. '),
('Besta frænka hallaði enn þá upp að veggnum í vinnustofunni. '),
('Ég dró fram blöðin sem besta frænka hafði skrifað handa mér. '),
('Amma kom yfir í herbergið til okkar ásamt Önnu frænku. '),
('Amma og Anna frænka horfðu hvor á aðra og sögðu ekkert. '),
('Á þriðja degi tilkynnti frú Margrét að ekki vænkaðist hagur Strympu. '),
('Ég er frænka þín, hún er systir mín. '),
('Ég set þær í vasa fyrir þig, frænka, segir hún. '),
('Ekki fleiri sögur, sagði nú besta frænka hratt með höndunum. '),
('Á þröskuldinum leit besta frænka til mín viðvörunarauga. '),
('Hugsaðu þér, hvað frænka og frændi verða glöð. '),
('Rut vildi fá samþykki frænku sinnar. '),
('Frænkurnar á fyrstu og annarri hæð vinna báðar á vöktum. '),
('Þú ert ekki með öllum mjalla, frænka. '),
('Frænka, leyfðu mér að hjálpa þér. '),
('Frænkurnar keppast alveg um mig. '),
('Hann tók saman við frænku sveitaprests. '),
('- Þess gerist ekki þörf, frænka. '),
('Þú ert í þungu skapi, frænka, mælti Eyjólfur. '),
('Þá fyndist frænkunum líka svo gaman. '),
('Þetta er eitthvað fyrir frænkurnar, sagði Óskar. '),
('Þessi frænka átti engin börn og vildi gjarnan hjálpa mömmu. '),
('Hvernig vissi hún að besta frænka var móðir þín? '),
('Við verðum að bíða þangað til frænkurnar koma af vakt, sagði Óskar. '),
('Þá þótti bónda mjög vænkast. '),
('Það eru dökkir blettir á lökunum og allt angar af barnaolíu. '),
('Þar var mynd af riddara, sem hleypti fram á harðastökki. '),
('Hárið var dökkjarpt að lit, þykt og mikið. '),
('En hún er góð á stökki. '),
('Móarnir eru orðnir dökkir, grundirnar gular og engin sinugrá. '),
('Þeir riðu til baka á harðastökki. '),
('Baugarnir undir augunum eru dökkir og þrútnir. '),
('Þarna tók ég annað stökkið. '),
('Af hverju, veslingur litli, segir hann, ætlarðu að tortíma þér með heljarstökki? '),
('Hver var dökki maðurinn fyrir utan völlinn rétt fyrir hvellinn? '),
('Og litli þeldökki drengurinn sagði: '),
('Við vorum komnir til hans í einu stökki. '),
('Skinnið var farðalaust og gróft og dökkir baugar undir augunum. '),
('Já, hann reið hesti á harðastökki. '),
('Og dökki skugginn á flóanum reis og varð að flóðbylgju. '),
('Hesturinn frýsaði, prjónaði einu sinni, og þaut af stað á stökki. '),
('Hann var sveittur við hársrótina, dökkir blettir voru á skyrtunni. '),
('Þarna komu þeir, ríðandi á stökki út úr hrárri morgunþokunni. '),
('En þrátt fyrir sviðann í augunum hafði hann séð Karl gegnum reykmökkinn. '),
('Ég leit við þegar við gengum upp tröppurnar að neðstu veröndinni. '),
('Hann lagði þykka skýrslumöppuna á skrifborðið og opnaði gluggann. '),
('Hún snýr sér við og fer niður tröppurnar. '),
('Mamma opnaði dyrnar áður en ég kom að tröppunum. '),
('Það er glerhált á tröppunum eins og víðast í borginni. '),
('Þeir fara niður að klöppunum, þar sem sjórinn er aldrei alveg kyrr. '),
('Við gengum hægt niður tröppurnar. '),
('Það var of kalt til að fara út á tröppur. '),
('Hann hrasar en Sollu tekst að halda honum á löppunum. '),
('Hún snýr sér við á klöppinni og hugsar eitt ævilangt augnablik. '),
('Við lötruðum á eftir þeim út á tröppurnar. '),
('Lóur vöppuðu, tófa gaggaði, krummi krunkaði og smali smalaði. '),
('Hann settist á tröppurnar í sólskininu og kveikti sér í pípu. '),
('Gestirnir klöppuðu yfir sig hrifnir. '),
('Dóttir hans kom út á tröppurnar og fagnaði honum. '),
('Stúlkurnar klöppuðu saman lófunum af kæti. '),
('Mjúkar hendur struku kinnar hennar, klöppuðu henni huggandi á höfuðið. '),
('Nei, ég er ekki leið, ég er bara svolítið slöpp. '),
('Svo sest hann í sófann, opnar möppuna. '),
('Við hlógum öll og klöppuðum fyrir honum. '),
('Katrín hripaði athugasemdina á miða og stakk í möppuna. '),
('Þú skaust nú sjálfan þig í löppina! '),
('Þá opnar Raggi gráu skjalamöppuna sem liggur á borðinu fyrir framan hann. '),
('Röddin var rám og slöpp, hreimurinn þriggja landa. '),
('Hann tók að velta undir klöppinni. '),
('Hann varð að styðja hana upp tröppurnar og inn í húsið. '),
('Hann lagði möppuna frá sér og sló inn orðið á lyklaborðið. '),
('En það er bara í þessari möppu. '),
('Tveir þeir stærstu hlupu upp marmaratröppurnar, hinir fylgdu á eftir. '),
('Hann stóð ekki lengur á tröppunum. '),
('Hann stóð kyrr og horfði á hana ganga upp breiðar tröppurnar. '),
('Hún gengur niður tröppurnar og opnar kjallaradyrnar. '),
('Moldarkögglar flæktust fyrir löppunum á manni. '),
('Einhverjir stöppuðu af sér í framdyrinu. '),
('Hamingjan sanna, og ég sem ætlaði að fara að gera kartöflustöppu. '),
('Sex tröppum síðar voru þær komnar inn í garðinn. '),
('Dreglarnir fengu að dúsa óáreittir úti á tröppum fram í myrkur. '),
('Þú átt ekki að sitja hérna hjá mér á tröppunum. '),
('Sumu fólki finnst hún afslöppuð og skemmtileg kona. '),
('Eftir örskamma stund birtist hann aftur úti á tröppunum. '),
('Fintan brosir og gengur niður tröppurnar á skólalóðinni. '),
('Hún lagði böggulinn frá sér og settist á klöpp. '),
('Vegurinn lá í kröppum beygjum. '),
('Hún vafraði um og stóð varla á löppunum. '),
('Bára hneppti frá efstu kápuhnöppunum og festi næluna í peysuna. '),
('Vegurinn lá upp á Haftið í kröppum beyjum. '),
('Þeir klöppuðu og fögnuðu og blístruðu á ný, hærra en fyrr. '),
('Hilma kom á móti henni í tröppunum. '),
('Áheyrendur í salnum klöppuðu og settu upp samúðarsvip. '),
('Loks kemur Björg út á tröppurnar, með fangið fullt af varningi. '),
('Þau hlógu og klöppuðu saman lófunum. '),
('Maðurinn hraðaði sér niður tröppurnar og skimaði í kringum sig. '),
('Reið bóndi skammt frá klöpp þessari og leit þangað. '),
('Á tröppunum voru konan hans og fimm ára dóttir. '),
('Pabbi hennar settist á tröppurnar við hliðina á þeim. '),
('Margar aldir þjöppuðust saman í eitt svipult andartak. '),
('Einhver hefur mokað snjóinn af tröppunum, hugsa ég. '),
('Hann var einn með rifflinum og nokkrum fuglum sem vöppuðu í kring. '),
('Hún opnar dyrnar og gengur prúðbúin upp tröppurnar. '),
('Hann hefur handritin sín í tveimur þykkum pappamöppum. '),
('Hún stökk upp tröppurnar en á stigapallinum tók ekki betra við: '),
('Hún stóð fullklædd á tröppunum þegar hann kom í hlaðið. '),
('Hann fer í skyrtu og setur á hana flibba með flibbahnöppum. '),
('Maður gengur niður tvær eða þrjár tröppur. '),
('Á klöpp við ána var villt reynihrísla, ein að veslast upp. '),
('Börnin klöppuðu og kölluðu nafn hans. '),
('Maður á fimmtugsaldri opnaði dyrnar og kom út á tröppurnar á sokkaleistunum. '),
('En hann vissi að kláraði hann stöppuna fyrst yrði lokaorrustan töpuð. '),
('Þar standa bækur, bréfamöppur og pappabox í röðum. '),
('Hann tók tröppurnar í nokkrum skrefum og keypti farmiða. '),
('Rétt upp úr miðnættinu fórum við Björg út á tröppur. '),
('Þeir sem við borðið sátu klöppuðu og hlógu, stöppuðu í gólfið. ');